### ISSUE TITLE
Next.js dev server gets stuck after a while, requests just spin

### ISSUE THREAD

**Issue by mjm** [zeit/next.js#10061]
# Bug report

## Describe the bug

When I run my Next.js app with `now dev`, after a while (on the order of minutes, definitely less than an hour) my requests to it will stop working.

## To Reproduce

I'm not sure how to isolate this one. It happens all the time with this project https://github.com/mjm/courier-js but it's not an easy thing to get running for reproduction.

1. Run `now dev`
2. Work on the app, making changes to files, saving, and watching them hot reload in the browser
3. Eventually, one of these changes will try to reload and will get stuck. The on-page indicator for a page compiling will be there and keep spinning continuously. Trying to refresh the page just causes the browser to try to load the page until it times out.

When I give up, I can hit Ctrl-C to try to kill the server, but if it's in this state, it can take a minute or two to actually get the message and quit.

## Expected behavior

Continuing to make changes should keep working and trigger refreshes in the browser.

## System information

- OS: macOS Catalina, though I think this happened before upgrading too
- Browser (if applies): I've seen in both Chrome and Safari
- Version of Next.js: 9.1.7, has happened in earlier versions of Next 9 as well
- Version of Now CLI: 16.7.3

## Additional context

I feel like this could be TypeScript related, but I don't have any evidence. I'm on the latest release for that as well. I'm happy to try things that might help understand what's going on. The only thing I've seen in the log from `now dev` (or `next dev` I guess) is that it seems like when it gets in this state, it will stack up two or three "compiling ..." messages when there would otherwise be just one.

**Comment by timneutkens** [comment]
Might help to eliminate if it's `now dev` of `next dev` related by trying to run your app with just Next.js.

**Comment by jeantil** [comment]
Hi, 

I have the exact same issue, after running `next dev` directly I don't have the issue anymore.

**Comment by MatteoGioioso** [comment]
Same issue here

**Comment by tetigi** [comment]
Likewise, same issue - seems intermittent and not tied to any particular change. It will work for a while, and then hang on the next change. Rerunning `npm run dev` again fixes it for a time, but it's a little irritating to have to continually reload.

`next dev` doesn't fix it for (same issue).

**Comment by timneutkens** [comment]
I've figured out a way to reproduce this a bit, will try to solve the issue.

**Comment by omarefg** [comment]
Same here

**Comment by cronokirby** [comment]
This seems to happen on a project I work on as well. Usually starts taking a lot of memory and CPU as well.

**Comment by timneutkens** [comment]
Having trouble consistently reproducing it to investigate, if you run into it please provide steps to reproduce or a repository, I'd love to investigate further but I could only investigate it about 5 minutes while trying for 2 hours.

**Comment by omarefg** [comment]
Hello @timneutkens [here](https://github.com/omarefg/next-issue) is a repository with the issue. You just need to navigate through the routes and the issue should appear.

I'm using Ubuntu 19.10 and Chrome 81.0.4044.113

Steps:

1. From home go to about
2. Go back to home
3. Go to story

If you do this while watching the network tab on the dev tools you'll see it get stuck on pending request and the only way to move on is to restart the server.

Let me know if you need more information or something.

**Comment by omarefg** [comment]
Hello @timneutkens here is a repository with the issue. You just need to navigate through the routes and the issue should appear.

This using ``next dev``

I'm using Ubuntu 19.10 and Chrome 81.0.4044.113

Steps:

From home go to about
Go back to home
Go to story
If you do this while watching the network tab on the dev tools you'll see it get stuck on pending request and the only way to move on is to restart the server.

Let me know if you need more information or something.

**Comment by omarefg** [comment]
Hello @timneutkens [here](https://github.com/omarefg/next-issue) is a repository with the issue. You just need to navigate through the routes and the issue should appear.

This using next dev

I'm using Ubuntu 19.10 and Chrome 81.0.4044.113

Steps:

From home go to about
Go back to home
Go to story
If you do this while watching the network tab on the dev tools you'll see it get stuck on pending request and the only way to move on is to restart the server.

Let me know if you need more information or something.

**Comment by winjingjie96** [comment]
Hello I am facing the same problem too! 
Been learning Next for two hours now and I thought I installed it wrongly. The issue can be mostly reproduced (in my case) by writing incorrect React code so that it compiles with errors. After correcting it, the hot reload function goes abit wonky and I have to kill the dev server (sometimes multiple times) to get it to work again.

My dependencies are as follows:
`  "dependencies": {
    "next": "^9.3.6",
    "nprogress": "^0.2.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }`

Just for comparison, Gatsby's start script works extremely well on my computer (not sure if this is worth anything)

Should I downgrade from 9.3.6 to a stable version? 

(This is my third month self learning coding so if I sound dumb I apologise)

**Comment by neupauer** [comment]
Hi, I have the exact same issue, even in the clean Next.js starter app (`npm init next-app`, no additional dependencies)

### To Reproduce
Run `npm run dev` or `next dev` and then refresh the page few times (hit _CMD+R_ quickly, at least 10 or more times) the dev server gets stuck (requests have a `pending` status)

### System information
- OS: `macOS Catalina`, Version 10.15.4
- Version of Next.js: `9.4.2`, I had the same problem in previous versions of Next.js
- All dependencies:
```
"dependencies": {
  "next": "9.4.2",
  "react": "16.13.1",
  "react-dom": "16.13.1"
}
```

### Solution
I am not sure, but it seems to work in my case. When I start server with different port (not the default `3000`) it works like a charm `next dev -p 1234`

**Comment by eandre** [comment]
I ran into this problem as well, and it was caused by an old cached service worker. I cleaned the cache completely (under dev tools -> application in Chrome) and the problem was fixed. Not sure if your problem is due to the same cause.

**Comment by pablopunk** [comment]
I've been dealing with this issue for a long time. Latest nextjs, fresh install of macOS 10.15.4, it happens all the time, it's a PITA.

The only thing that worked for me was @neupauer's solution, running dev server on another port (in my case `npx next -p 1234` works).

🎉

**Comment by eandre** [comment]
@pablopunk have you tried cleaning out the cached service worker? That cache will be port-specific, so by changing the port you're working around the problem. Curious to see if this is the root cause for others or just for me.

**Comment by pablopunk** [comment]
@eandre I have and I think the issue came back eventually. Anyway, this is an issue on next.js and should be solved

**Comment by eandre** [comment]
Of course it should be solved! I'm just trying to help find the root cause. 🙂

**Comment by HunderlineK** [comment]
I'm having this issue with 'Vue' as well; so I wonder if it is not a next.js issue but a vercel dev issue

**Comment by jgillich** [comment]
@HunderlineK This also applies to `next dev`. But it's interesting that Nuxt has the same issue, might be some shared dependency that's causing this?

**Comment by pi0** [comment]
Hi :) Just to summarize there was/are 3 well-known issues which might be shared:

 - https://github.com/fsevents/fsevents/pull/290
- Registered service worker (usually production mode) on same port and try to run `dev`
- Connection/Socket limit 

Still, as there is no proper way to reproduce these were just some clues we found. It might be also a generic chrome bug.

**Comment by jgillich** [comment]
webpack-hot-middleware uses up one of the 6 connections via [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource), and when all are used up it results in the browser being unable to establish more connections and therefore an infinite loading spinner: https://github.com/webpack-contrib/webpack-hot-middleware/issues/298

Maybe there's a rogue service worker that hogs up more and more connections over time and never releases them. Just guessing though.

**Comment by pi0** [comment]
@jgillich Exactly EvenSource is probably a cause. For nuxt there is also an additional SSE handler for loading-screen/indicator. (next release will use new port but it also brings its own problems...). Just to give some more context, previously we were using Websockets and the issue was less visible...

**Comment by HunderlineK** [comment]
@pi0 I have this issue on FF as well. In my case at least, once it happens, it just fails across all of the other browsers that I have i.e. Chrome, Edge and Safari.

I also know this only happens once there is a change in the source code.

I have also had this problem with using 'vercel dev' only for the API; i.e. I had my dev server separately setup for serving the front end and then vercel for the API and ended up in a situation where front end was working but API was stuck 🤷‍♂️

**Comment by pi0** [comment]
@HunderlineK I also experience that but I think it is another issue... Hope we can finally find root-cause(s) together :)

**Comment by opolo** [comment]
We are facing the same issue... Everytime we have a new release, our platform cannot load any new pages on the client machines until they refresh their cache. As we are a B2C company, its hard to notify and teach the users about this...

**Comment by timneutkens** [comment]
> We are facing the same issue... Everytime we have a new release, our platform cannot load any new pages on the client machines until they refresh their cache. As we are a B2C company, its hard to notify and teach the users about this...

This sounds unrelated to the issue @mjm reported which only manifests in the development server, which I doubt you're running in production. Can you create a discussion on https://github.com/vercel/next.js/discussions with clear and concise reproduction steps.

**Comment by opolo** [comment]
Ah, thanks, will do!

**Comment by acha5066** [comment]
Running version: 9.3.5

One way this seems to continually happen is if I delete a file that is imported somewhere in my app, without removing the import statement. Doesn't seem to happen every time but that is the most common scenario where it has occurred. After that it usually gets stuck in the compiling stage.

I'm running the vercel dev command by the way.

**Comment by ColeTownsend** [comment]
FWIW, I'm experiencing this on zeit 9.4 with a customer server on both Chromium and Safari. I cleared my cache and also tried on incognito in both browsers.

Ran `next dev`, `next dev -p XXXX`, nuking the repo, nuking `node_modules` and `.next`, and changing my node version to various stops between 12 and 14.

**Comment by w3ea** [comment]
Version: 9.5.2

Same here
after a while, especially when inspect is open, it gets stuck
I tried to run it on the different port `next dev -p *` but didn't change

it's really annoying 😒

**Comment by samuanv** [comment]
+1
Running latest version (`9.5.3`) and I am getting this problem too.
I think it might be related to Sass. 
When I comment out my global `@import` for external library styles it works properly.

**Comment by timneutkens** [comment]
> Having trouble consistently reproducing it to investigate, if you run into it please provide steps to reproduce or a repository, I'd love to investigate further but I could only investigate it about 5 minutes while trying for 2 hours.

Posting +1 or "same issue" is not helpful. Please provide a reproduction so that it can be investigated.

**Comment by Temetias** [comment]
Yup facing the same issue here and all it takes to reproduce for me is just running `npx create-next-app [project-name]` and then trying to `npm run dev` that. So basically the starter seems to be unusable currently for me at least.

More info:
`npx next --version` - Next.js v9.5.3
Browser - Firefox 80.0.1
OS - Windows 10, running the stuff in WSL (Tested running Sapper in the same port and it seems to be fine so I doubt it's related to my system there)

Hopefully this helps in the investigations.

**Comment by timneutkens** [comment]
> Yup happening to me too and all it takes to reproduce for me is just running `npx create-next-app [project-name]` and then trying to `npm run dev` that. So basically the starter seems to be unusable currently for me at least.
> 
> More info:
> `npx next --version` - Next.js v9.5.3
> Browser - Firefox 80.0.1
> OS - Windows 10, running the stuff in WSL (Tested running Sapper in the same port and it seems to be fine so I doubt it's related to my system there)
> 
> Hopefully this helps in the investigations.

Can you check if you have a leftover serviceworker or reverse proxy in front of the application?

**Comment by Temetias** [comment]
> 
> 
> > Yup happening to me too and all it takes to reproduce for me is just running `npx create-next-app [project-name]` and then trying to `npm run dev` that. So basically the starter seems to be unusable currently for me at least.
> > More info:
> > `npx next --version` - Next.js v9.5.3
> > Browser - Firefox 80.0.1
> > OS - Windows 10, running the stuff in WSL (Tested running Sapper in the same port and it seems to be fine so I doubt it's related to my system there)
> > Hopefully this helps in the investigations.
> 
> Can you check if you have a leftover serviceworker or reverse proxy in front of the application?

Hm, actually after a full reboot it started working for me suddenly... The only thing i noticed being different is the output on the console. In the "stuck" scenario I only got:
`ready - started server on http://localhost:3000
event - compiled successfully`

But now when it's working it's also building the index page when the request comes in (as expected). It didn't do that previously tho.
`ready - started server on http://localhost:3000
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully`

Before it started working again I did check and there was no leftover serviceworkes at least. I did also try with a fresh install of chrome and same thing.

I know that it's not much to go by and I wish I could provide more help with this.

**Comment by yuriduarte** [comment]
Hello, I have the same problem, in my case it happens when I do some import of styles within a page or component and almost every time I try to change these styles the browser keeps loading endlessly ...

Sometimes the problem occurs when I update some part of the code that has an import from another part of the code.

For me it worked by clearing the service work cache in the browser.

**Details**:
- Browser - Google Chrome Version 85.0.4183.121 - 64 bits
- OS -macOS Catalina version 10.15.6
- Next.js v9.5.3
- React v16.13.1
- React DOM v16.13.1

I hope that this information helps in the investigations, I investigated a little here as well but I still haven't been able to dedicate myself to it, if I have any solution for the case I say here.

**Comment by s4l1h** [comment]
I had the same problem too. I have fixed this problem by remove service worker. 
When you change the development server port if the problem gets solved. The problem occurs because of the old service worker.

For Chrome.
Open this page: **chrome://serviceworker-internals** and find localhost service workers and click to **unregister button**.

If you want to unregister all service worker open the **developer tools** and run this code on above page.

    document.querySelectorAll("button.unregister").forEach(item=>{ item.click()})

**Comment by kylekirkby** [comment]
For some reason, removing `jshint` with `yarn remove jshint` fixed my problem. I did just add it, so logically worked backwards regarding what had changed.

**Comment by orajiaku** [comment]
Hey guys, is there a fix for this? 
I am using `"apollo-server-micro": "2.19.0"` for my apollo server. It hangs after one successful connection.

**Comment by sheikalthaf** [comment]
I also faced the same issue. By unregistering the service worker from devtools for `localhost:3000` solved the issue.
You can also try the same by going to `devtools -> Application -> service worker` and then unregister if anything shown for `localhost:3000`.

This issue is solved for me by doing above process.

**Comment by gavinmn** [comment]
Started running into this issue recently as well. It seems as though when I start the dev server from a text editor (I've tried both VS Code and Nova) I hit this issue. Switching ports with `next dev -p xxxx` allows it to work on the new port, but only until I kill the dev server. Starting it back up on a port that has already been used causes me to hit the same error. 

I've checked for service workers, and there are none to clear off my localhost ports. 

Oddly enough running next dev on any port that I've used in the past directly from iTerm results in it working.

**Comment by SilverClash** [comment]
Running into the same issue here, today it just stopped working. When I try to build a project it's compiling successfully and the just get stuck on "Collecting page data". Dev server itself working, the initial page where I have only static data is working perfectly, but all other pages where GraphQL call used not working, can't receive any data.

Same project working just fine on another PC with all the same data sources, same network, same code. I tried to delete all packages, clean cache, install Next 10.0.5 or 10.0.4 - no luck, it's completely stuck. Changing port with -p xxxx is not working for me

**Comment by nuflowx** [comment]
Ran into the same issue a few days ago. Tried unregistering service-worker like others have mentioned, nothing. Clean, reinstall different packages, etc.

Changing port works fine, so for now I'm just doing that, would be good to figure out the source of the issue eventually... Or some fix. Workaround running on different port good enough for now though

**Comment by exonis** [comment]
For me it was the service worker that was completely messing with my browser creating huge memory leaks in the hundreds of MB, preventing the page to reload, preventing routes to work properly and other negative effects. I resolved all those issues when I stopped and unregistered the service worker in the chrome dev tools.

**Comment by nuflowx** [comment]
After trying my previous steps (un-registering service worker, reinstall, etc) what finally fixed the issue was a computer restart.
So can't pinpoint which of the things exactly resolved it, my guess would be service-worker solution as most people have mentioned that, but tied to a computer restart for me ;)

**Comment by elvisduru** [comment]
It appears the port 3000 is already in use. You can solve the problem by doing the following:
_On Windows:_
```
netstat -ano | findstr :3000
tskill typeyourPIDhere 
```

_On Linux/Mac:_
```
lsof -i tcp:3000
kill -9 PID
```

**Comment by Bestulo** [comment]
Problem persists lol. I have to restart my app after a little while of development. Using Next v10.

**Comment by Bestulo** [comment]
Problem is solved for me. I updated NPM from 6.14.11 to 7.6.0, and the dev server instantly stopped getting stuck every 15 minutes and it has been live and fast refreshing on changes for over 4 days without being restarted once. Sailing smooth now.

**Comment by lorstenoplo** [comment]
I am facing the same issue but only since 2days, you find the repo here : https://github.com/lorstenoplo/eccom-api

Same issue here, I have tried the following :
1. Starting with a different port
2. `next dev` doesn't work for me 
3.  There were no service workers on localhost itself, so I cannot clear them

**Comment by gulliverwald** [comment]
I was facing the same issue, after I updated yarn to 1.22.10 with `yarn policies set-version`, it seems to have improved a little. Although the fast refresh is not working 100%, the page still gets stuck and not respond, if that happens, after reloading it, it seems to get back to normal.

**Comment by digz6666** [comment]
Same issue on nextjs 10.0.6

**Comment by njustice4all** [comment]
I think this problem is due to the chrome extension
so check your browser i'm using chrome 89.0.4389.114
uninstall chrome extension all (do not disable, remove)

**Comment by amedina068** [comment]
I had the same issue for the last couple of months. Yesterday I finally had it and removed all node_modules, and package-lock, updated my npm to 7.x, stopped the service worker for localhost:3000, and started using npx next dev instead of npm run dev. And it seems the issue was solved.

It seems that what made it work was stopping the service worker and then restarting the npx next dev command. 

I don't know if it has anything to do with it but the first Next app I worked on was the PWA example and I worked on it for several weeks before disabling the PWA for development.

**Comment by meotimdihia** [comment]
I doubt this relates to production too. 
My website gets stuck on iPhone, and it works again if I open a new tab in private mode.
Currently, I dunno how to debug it on mobile.

**Comment by CaptainFoxy93** [comment]
Weird, when i do npm run dev, it starts normally but when i open localhost:3000 it just keeps loading, it doesn't give me any errors but i cannot access the web page

**Comment by CaptainFoxy93** [comment]
> 
> 
> Hello, I have the same problem, in my case it happens when I do some import of styles within a page or component and almost every time I try to change these styles the browser keeps loading endlessly ...
> 
> Sometimes the problem occurs when I update some part of the code that has an import from another part of the code.
> 
> For me it worked by clearing the service work cache in the browser.
> 
> **Details**:
> 
>     * Browser - Google Chrome Version 85.0.4183.121 - 64 bits
> 
>     * OS -macOS Catalina version 10.15.6
> 
>     * Next.js v9.5.3
> 
>     * React v16.13.1
> 
>     * React DOM v16.13.1
> 
> 
> I hope that this information helps in the investigations, I investigated a little here as well but I still haven't been able to dedicate myself to it, if I have any solution for the case I say here.

that happens to me too, i have my index.jsx importing Layout.jsx wich imports Navbar.jsx. Let's hope Vercel fixes it soon...

**Comment by vishalkhoje** [comment]
Hi

This same issue occurred for me because of code mistake.

I have created one function component Nav.js file

`function Nav() {
    return (
        <Nav>
            <h2>nav</h2>
        </Nav>
    )
}
export default Nav`

here the mistake is above code instead of **<Nav></Nav>** we need to use <nav></nav>. I accidentally return this and import into index.js file and the code is going into infinite server gets stuck after a while, requests just spin.
After change this correct code
`function Nav() {
    return (
        <nav>
            <h2>nav</h2>
        </nav>
    )
}
export default Nav`

 After this everything works charm. Check after which code added this issue occurred.
 Not sure if your problem is due to the same cause.

**Comment by spblewis** [comment]
I had this problem, or a very similar one. When I ran my CLI as admin I got a parsing error rather than the server simply hanging. Ultimately I determined there was a babel configuration (.babelrc) further up the directory tree. Installing in an unrelated directory worked immediately.  So would resolving the babelrc conflict, presumably.

**Comment by ilyandho** [comment]
I had the same issue but I found that on page that was causing the infinite loop, I had a poorly implemented for loop that went into an infinite loop.

**Comment by shivdon** [comment]
I had the same issue,
by deprecating the next version to 10.2.3 solved my error,
```
npm install next@10.2.3
```

**Comment by jwdotpark** [comment]
I don't really know about OS level resource management but it seems like it's happening in macOS or Linux as well, in my case I'm on wsl2 and shutting down it in Powershell by ```wsl --shutdown``` and boot wsl again made it work. 

Just rebooting the machine didn't work, I needed to kill wsl process and now it's working as intended.

I assume wsl is still a bit unstable regarding network configuration etc but who knows..

**Comment by matepaiva** [comment]
I am getting that a lot since I upgraded to nextjs@11, but I am not sure if it is because of nextjs@11 or next-pwa@5.2.21.

**Comment by dukemai** [comment]
I am having this problem on Mac also

**Comment by zainshabir00** [comment]
I had the same issue. I deleted the node_modules and package-lock.json file and re-installed the node_modules by runnnig `npm install` and now it refreshes the browser when saving any file.

**Comment by denis-sokolov** [comment]
Increasing the limit of open files on my OS fixed this for me.

(Lookup `ulimit`. For macOS lookup `launchctl limit maxfiles` and `sudo launchctl limit maxfiles`)

**Comment by leobenkel** [comment]
Is that solved ? 
I am having the same problem when running `netlify dev -e -p 4000`.
I tried to use `next dev -p 4000` but it crashes at launch with missing dependencies.  

The behavior is the same for me. The hot refresh works at first (when I change my code, the page update) but after a few minutes, it stops and the browser hangs forever when trying to reload the page manually.

**Comment by MananPyJava** [comment]
any advancements on this issue?

**Comment by maxprilutskiy** [comment]
Guys, you won't believe me, but I've just changed the port from `localhost:3000` to `localhost:4000` and the issue disappeared.

Magic ✨

**Comment by Mjeyz** [comment]
> I've been dealing with this issue for a long time. Latest nextjs, fresh install of macOS 10.15.4, it happens all the time, it's a PITA.
> 
> The only thing that worked for me was @neupauer's solution, running dev server on another port (in my case `npx next -p 1234` works).
> 
> 🎉

Thank you very much, friend; I'd been having this problem for a long time, but after implementing your solution, my app is now perfectly working on the local server. Thank you once again from the bottom of my heart.

**Comment by StrawberryChocolateFudge** [comment]
I have the exact same issue with `vercel dev`.  It's happening all the time. Requests just hang. Development experience is bad.
Solution that seems to work, specify the port:
`vercel dev --listen 5000`

**Comment by WalterIran** [comment]
I had the same problem, using `npm run dev`, when I entered localhost:3000 it just keep reloading without showing anything, I remembered that some days ago I had enable Windows Protection against ransomware on Windows Defender by enabling the controlled access to folders, I disabled it and then restarted `npm run dev` and it worked

**Comment by tonibardina** [comment]
I had the same issue, looks like I had some socket connections on `CLOSE_WAIT` mode (on port 3000). I killed them (`kill -9 <port>`) And now everything seems to be working just fine again

<img width="332" alt="Screenshot 2021-11-01 at 12 38 29" src="https://user-images.githubusercontent.com/29999392/139666309-83debbdc-13a9-4d9b-bb31-a133b1cfde58.png">

**Comment by Taro-Naza** [comment]
I'm running `"next": "12.0.3"` and I'm having the same problem, changing ports doesn't work. any idea on how to fix this?

**Comment by martijnspitter** [comment]
I had a naming conflict in my project with two components named home. This resulted in the same behaviour where the compiler got stuck after any file change or reload of the browser. The first render after a fresh restart still worked. Changing ports and clearing cache had no effect for me as you would expect with a naming conflict.

**Comment by sildeman** [comment]
I was having the same problem. I changed `npm` to `yarn` and everything started working again.

**Comment by talksik** [comment]
this is kinda of lame...same issue for a year...I have to create a new next app to make it work again

**Comment by talksik** [comment]
temporary fix: delete node_modules and then run npm i
then delete .next folder in the project

note that on windows it's harder to remove these files so I used git bash and then ran 'rm -rf node_modules' and 'rm -rf .next'
then 'npm i' then 'npm run dev'

**Comment by mad-briller** [comment]
Encountering the same issue on next.js 12, super frustrating to deal with as there is no indication anywhere what the problem is or how to begin debugging it. 

creating a production build and using `next start` works fine but `next dev` causes requests to spin forever,
deleting node_modules, .next and package-lock and reinstalling solves nothing. 

checking out known good versions of my code base (that didn't show this issue prior) and running `npm run next dev` doesn't work either. These two things bring me to the conclusion the issue cannot be within my code.

The next.js framework is extremely elegant but this one particular issue makes it very hard to trust it to develop applications on, because at arbitrary points it becomes unresponsive and impossible to progress or fix issues raised by customers, and instead must waste hours trying to fix a problem with no clear route to a solution.

**Comment by ijjk** [comment]
@mad-briller what version of Next.js are you leveraging? There are few known cases where this can occur which aren't all within Next.js' control:

1. A project that used `localhost:3000` registered a service-worker that caches requests and prevents new requests from completing correctly. (see here for [removing the service worker](https://stackoverflow.com/questions/33704791/how-do-i-uninstall-a-service-worker))
2. On older Next.js versions when multiple tabs are open to `localhost:3000` at the same time and they are all visible Chrome might limit new connections as they [limit the number of open connections](https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser) (this should be resolved in the latest version v12 as we use a WebSocket for HMR now which doesn't count against the limit)
3. A non service-worker related cache is present in the browser which can be avoided by using incognito mode or clearing the browser cache
4. A browser extension is interfering with the requests (disabling extensions and trying can resolve this)
5. A request is being done in `getServerSideProps`/`getStaticProps` that doesn't have a timeout/is stalling.

If none of the above help please provide additional information (OS, node version, Next.js version, a repo where this occurs, etc) to allow investigating!

**Comment by enahs** [comment]
This issue was opened like a year ago... how is it still busted lol.

here's some debugging help:
- i've tried this on hella node versions (all over 15, 16, 17) node ain't the problem

```
$ node -e 'console.log(process.version, process.arch, process.platform)'
v17.2.0 arm64 darwin
```

next version:
```
 $ npx next -v
Next.js v12.0.7
```
1. it ain't my browser — it's frozen when i `curl localhost:3000`

so if it's not my browser, it must be my code right? well, no. 

let's start with a clean install
```rm -rf ./node_modules/ .next/ ./package-lock.json && npm i```

when i do `npm run dev` it hangs. doesn't respond to curl. i see the listener on port 3000, via lsof -i :3000:
```lsof -i :3000
COMMAND   PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    20049 shane   23u  IPv6 0x5622c9dbee67c0eb      0t0  TCP *:hbci (LISTEN)
```
so the server is fired up, but i don't see this message ever:
```
event - compiled client and server successfully in 3.9s (580 modules)
```

seems to ignore SIGINT (ctrl-c); have to kill using the port and SIGKILL

wonder if it's the compiler??? also, randomly see some pages rendered wierd (think mobile styles) and have seen something about waiting for play.google.com while the browser was jamming... my paranoia tells me it's some android arm64 foolishness going on?

**Comment by guylil** [comment]
I don't know if it might help someone but, it does not happen when I reload at the main '/' page...
While working on other pages it reproduces (infinite 'waiting for localhost  in the browser') 
but I do get "event - compiled client and server successfully in 394 ms (188 modules)" in the terminal...

(I guess that might be webpacks' problem...)

I hope I'll have more time to investigate later today

**Comment by PaliwalSparsh** [comment]
I have tried all the things up here. It still loads infinitely. It worked once when i used next dev -p 3001. But, later even that stopped to work this is really strange.

**Comment by dukemai** [comment]
> I have tried all the things up here. It still loads infinitely. It worked once when i used next dev -p 3001. But, later even that stopped to work this is really strange.

I think I had same problem as yours then I recognized it was services worker that listens on port 3000 causing this problem, I just unregister that then it works again

**Comment by tamimaj** [comment]
> Can you check if you have a leftover serviceworker or reverse proxy in front of the application?

Thank you! @timneutkens  That works perfectly!
So, I was not developing nextJS on mac because of the freezing issue and hot-reloading not working. In Windows, the same code was working perfectly. When I saw your comment about service workers. I investigated it, and for me, it was what caused the freeze. In my mac, I used to develop some react stuff with service workers on the same port 3000 (the default). When removed the service worker registered on that port, everything worked perfectly.

So if you have the next-PWA plugin working on production mode only as suggested, and you build the app and run it with "next start" the service worker gets registered on MAC, even it is localhost. On Windows that does not happen, I searched the internal service workers and not a single localhost was registered.

If you are using mac after each production build and start, you have to unregister the service worker on the port. Or run dev and production on different ports.

**Comment by matt-way** [comment]
I've only hit this issue for the first time in a year, and it is really strange. If I put a console.log as the first line of my `getServerSideProps` function, the page loads fine. If I remove the log it hangs. Never seen a bug like this before...

**Comment by ainsleyrutterford** [comment]
I only had this issue when I updated to Next.js 12.1.5. Reverted back to 11.1.2 and the dev server no longer hangs

**Comment by EdwardJoko** [comment]
I solved this issue with `npx kill-port <port>`. So far this solution works (3 hours). The other solutions above that I tried only worked for some minutes.

**Comment by arkhon7** [comment]
any updates on this issue?

**Comment by ColeTownsend** [comment]
You can run `yarn build` then `yarn start`

**Comment by inkiltie** [comment]
I got a similar issue but it was causing my app to show "No Internet" message on localhost after any file update in VS Code. And if `kill-port` or changing port doesn't work and you had SW previously installed, maybe, just maybe, SW left your network state in offline mode. Even though the Offline mode checkbox unchecked in Application tab, go to the Network tab and change from `offline` to `no throttling`.

In my personal experience with SW in Chrome, if you tested offline mode once, it may then be following you forever. I got SW unregistered and deleted, but still it could manage to set my Network to offline mode, and it applies to entire localhost. Even if my Next app on `:3000`, but GraphQL on `:5001`, all was down.

**Comment by Aketca** [comment]
> You can run `yarn build` then `yarn start`

We realize we can run 'yarn build' then 'yarn start'. Also, we can run 'yarn dev' and get this problem.

**Comment by Aketca** [comment]
I have a suggestion about it, it may happen when a request in getServersideProps has an error response (like auth 401). I read the documentation, which said to avoid these cases

**Comment by lachlansleight** [comment]
I've been absolutely losing my mind regarding this issue for YEARS now - would have the same problem everyone describes. The only solution I found to regularly work was to restart my PC and then delete the `.next` folder before opening my IDE.

**However I found the cause of the problem today (at least, on my machine): **

My automatic backup software was in the process of uploading the contents of .next, preventing nextJS from accessing the folder and hanging in some mysterious way.

I paused my backups for an hour and ran `next dev` again - it worked no problems. :)

This issue could be solved for me if next.js was able to somehow detect that the contents of `.next` were in-use by another application and throw an error if so.

**Comment by Mankuda** [comment]
#music

**Comment by Aketca** [comment]
Guys, I had that problem when in getServerSideProps I sent a request, which catch a fail (like 401 or something like that, it was a very rare event in my project). And my Axios interceptor was trying to refresh the request. As I know in getServerSideProps we need to request only data, without any auth logic, is it correct?

**Comment by suresh-suthar05** [comment]
Hi 
I have some issue when i reload page then i fetch long time page waiting process....... 1 min waiting  then page reloaded.
How to fix this issue ?

**Comment by sasamon0827** [comment]
Hi 
I have same issue after updating from next.js 11 to next.js 12.

OS: `macOS Catalina`, Version 10.15.7
Version of Next.js: `12.1.6`

I tried `next dev -p 1234` but it can't solve issue.
Is there any solution for that??

**Comment by sasamon0827** [comment]
Hi
After updating OS from Catalina to Monterey, this issue was solved somehow.
Now I'm using the following environment.

OS: `macOS Monterey`, Version 12.4
Version of Next.js: `12.1.6`

I'm not sure but there is something dependency with OS.

**Comment by huntharo** [comment]
It looks like all of the users with the problem have this in common:

- Mac OS
- 100% CPU loop that lasts several minutes
- Does not respond to Ctrl-C (observed by some as "port 3000 still in use" when trying to restart)

The problem is this:

https://github.com/nodejs/node/issues/43916

There is a loop when a libuv write function on Mac returns `EPROTOTYPE`.  There was unsafe code that would infinitely loop in native libuv code (never going back up to V8, not even on Ctrl-C interrupt).  It looks like Mac OS may have changed this edge case OR some VPN software aggravates this (as reported in libuv's tickets) OR something about `next.js` causes this condition to get hit more often.

libuv already found and fixed this problem, but the fixes are not yet in `node`:

- https://github.com/libuv/libuv/pull/3405
- https://github.com/libuv/libuv/pull/3413

If you want to see if this is causing your problem, do the following:

- Install Xcode if you have not already
- Install Xcode CLI tools if you have not already: `xcode-select --install`
- Monitor for `node` going into a 100% CPU loop with Activity Monitor
- When node is in a 100% CPU loop
  - Get the PID of node from Activity Monitor
  - Attach a debugger: `lldb -p [pid]`
    - Note: this does not have a to be a special local build, the standard builds of node are note stripped so you will be able to see at least function names
    - When the debugger attaches the process is paused automatically
    - Run the `bt` command to get a backtrace for the current thread
    - You should see `uv__try_write` at the top of the stack if this problem is impacting you
    - To confirm, repeat these a few times and you should see it continue to be in the same place:
      - `continue`
      - `process interrupt`
      - `bt`
      - Repeat a few times - It should always be in the same place
      - `kill` to detach and kill the node process

### Running `bt` in `lldb` - Stack of infinite loop

![image](https://user-images.githubusercontent.com/5617868/180089159-96c0cf36-337f-48e8-b4d4-0b8be8131adf.png)

**Comment by jgillich** [comment]
> It looks like all of the users with the problem have this in common

There are several users experiencing this issue on Linux and Windows in this thread (including myself)

**Comment by huntharo** [comment]
Here is how to test the Mac fix (or even just use it until it's patched) for those on Mac:

## Diff of changes to 1 file

https://github.com/nodejs/node/compare/v16.x...huntharo:node:v16-mac-loop-fix?expand=1

## Build Instructions

1. Clone my fork: `git clone https://github.com/huntharo/node.git`
2. Move into the repo: `cd node`
3. Install Xcode if not installed already
4. Install Xcode devtools if not installed already: `xcode-select --install`
5. Ensure `python3` is installed: `python3 --version`
    1. The build docs are not super clear... but you may need to `alias python=python3` 
7. Checkout the fix branch: `git checkout v16-mac-loop-fix`
8. Configure a non-debug build: `./configure`
9. Run the build with parallel compiles: `make -j8` (8 is good on M1 Macs, use `-j4` on non-10 core machines)
10. This should result in `./out/Release/node`
11. To check the architecture of the built version of node(particularly on M1 to make sure you didn't build for Intel via Rosetta): `file ./out/Release/node` - Should output:
    1. M1: `./out/Release/node: Mach-O 64-bit executable arm64`
    1. Intel: `./out/Release/node: Mach-O 64-bit executable x86_64`
12. The build takes about 5-15 minutes on an M1 Pro
13. Once built, add this build `node` to your PATH before any other version of node in the terminal where you are going to run `next.js` apps: `export PATH="$HOME/node/out/Release:$PATH"
14. Check the version of node run by default: `node --version`
     1. Should output: `v16.16.1-pre`
15. Run your `next.js` app and confirm if the infinite loop problem is resolved

**Comment by Zulaxy** [comment]
Deleting .next folder in the project and then running npm run dev simply worked for me.

@talksik, Thank you!

**Comment by huntharo** [comment]
Anyone having this problem on a Mac: try the node 18.7.0 release just to see if the problem goes away as the infinite loop in native code fixes are in that version.

https://github.com/nodejs/node/releases/tag/v18.7.0

**Comment by rgbskills** [comment]
For me it was caused by an image (used next/image) not loading due to a missing file, once I fixed it the problem went away.

**Comment by professorhaseeb** [comment]
this issue still exists on next13

**Comment by iamawaisakram** [comment]
For me this was the usage of `react-toast-notifications` package usage, removing it resolved this issue for me.
If you recently added a package, do checkout by removing it first.

**Comment by vxna** [comment]
> 



> If you recently added a package, do checkout by removing it first.

Sheeesh, `@next/font` was the culprit in my case 🤦‍♀️

**Comment by antokhio** [comment]
Hi, just run `yarn create next-app``yarn dev` open browser `http://localhost:3000` and nothing… windows 10

**Comment by dezintegro** [comment]
> @next/font was the culprit in my case 🤦‍♀️
that's it
removing `@next/font` solves the problem

**Comment by machineghost** [comment]
For me the issue was a sub-component with a `require` in it (specifically `const { default: styled } = require('styled-components');`).

I figured it out when I noticed I could load some pages on my devsite just fine, but when I went to one certain page it locked everything up and made it impossible to kill the devsite (even with `CTRL + C`).

I then simplified that page to be a "hello world", and saw an error from another component it used to be using (not sure how I even got that error; I guess just from the import?).

I fixed the error (the `require`) and my devsite went back to normal, `CTRL + C` and all :)

**Comment by joost-berg** [comment]
For anyone struggling with this in 2023. Updating node to v18 solved the problem for me on Mac Pro m1 / Ventura

**Comment by khuezy** [comment]
This is happening to my all of a sudden... Nothing changed. I saw an error saying that the `@next/font` wasn't compatible w/ a next-canary version. Tried using the latest node version and reverting to an older version that had the fix but the `node` process is stuck at 100% CPU

**Comment by VladislavKorecky** [comment]
For me, the issue was really weird. When I ran `lsof -i tcp:3000` there was a node instance running (probably NextJs) but when I ran `npm run dev` I didn't get an error. NextJs started just fine. I somehow got two NextJs instances running at the same time, so when I tried to reach 127.0.0.1:3000, it just wouldn't load. I killed that process and the issue was fixed.

**Comment by Rohith-JN** [comment]
I encountered the same issue,

**Comment by ahmedelbougha** [comment]
> For anyone struggling with this in 2023. Updating node to v18 solved the problem for me on Mac Pro m1 / Ventura

Upgrading to nodev18 fixed the problem for me ( Ubuntu 22.04)

**Comment by janwirth** [comment]
No, I'm still having this problem. next@13.2.1

**Comment by curiousercreative** [comment]
> No, I'm still having this problem. next@13.2.1

next@13.2.4 is the latest release.

**Comment by janwirth** [comment]
Actually, i figured out that the problem was some misplaced JSX created by VS code autocomplete. So it was a parsing error that has the compiler get stuck somehow.

**Comment by Stroik** [comment]
It's 2023 and I'm still getting this error.

![](https://i.imgur.com/rJHmy4W.gif)

```
$ node --version
v19.8.1
$ npm --version
8.19.2

// package.json
"next": "13.2.4",
"react": "18.2.0",
"react-dom": "18.2.0",
```

OS: Windows 11 x64

I already tried to change the next port in the package.json scripts to 1234 or 8888 or 5000 and so on but nothing changes.
The only way that I found to stop the compiler is restart the dev server.
I reviewed all my code and there isn't syntax errors. I don't know what else to do 🥹

**Comment by carrizoja** [comment]
> Deleting .next folder in the project and then running npm run dev simply worked for me.
> 
> @talksik, Thank you!

This worked for me! Thanks!

**Comment by Stroik** [comment]
Manually disabled prefetch in whole application `<Link prefetch={false}>` worked for me. For some reason next.js 13.2.4 has the hover prefetch activated by default in dev mod and that bring the compiling issue

**Comment by sophlanz** [comment]
Fixed it by deleting .next folder and rebuilding it using 'npm run build". I would also recommend deleting node_modules, and reinstall with "npm i"

**Comment by danielgangverk** [comment]
Upgrading from node 14 to node 16.6.0 solved the problem for me. This only started happening after the new nextjs image component from nextjs 13 was introduced to the project

**Comment by mikeconstable** [comment]
Disabling my home VPN enabled localhost to load. Will not load if VPN is reconnected. Suggests external dependency such as a font being blocked as @iqqmuT flagged. I have a fresh 'create-next-app' install, no other dependencies added.

**Comment by ibrahimaq** [comment]
I came across the same issue. In my case, when I checked the 'network' in the console I noticed that the throttling was set to 'slow 3G'. I did use throttling some time ago and reverted it to 'no throttling' but for some reason it throttled on this occasion. Hence it seemed it was stuck in the loading state.

**Comment by mkarajohn** [comment]
> For me, the issue was really weird. When I ran `lsof -i tcp:3000` there was a node instance running (probably NextJs) but when I ran `npm run dev` I didn't get an error. NextJs started just fine. I somehow got two NextJs instances running at the same time, so when I tried to reach 127.0.0.1:3000, it just wouldn't load. I killed that process and the issue was fixed.

Same issue, same resolution.

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

**Comment by dvenomb98** [comment]
I cant really upgrade to node v-18 cause some dependecies in my project, but what worked for me is downgrading node to v16.15 from v16.44.

i did exact this:
cd (path-to-my-project)
rm -rf .next
rm -rf node_modules
npm cache clean --force
sudo n 16.15 (or your alternative)
npm install

"next": "12.3.1",
"react": "17.0.2",
"react-dom": "17.0.2",

**Comment by jjroley** [comment]
I had this problem, for me it was because I accidentally had created an asynchronous client component (switched from a server component and forgot to make it synchronous.) I didn’t get any error messages, so it was a bit tricky to debug.

**Comment by pyriceti** [comment]
On my side, it was a leak from my postgreSQL database clients pool, so when I would be out of clients from the pool, the app would become unresponsive. This was hard to track, since most of the next app is cached (especially route endpoints from Link components) so only my API requests would never succeed.

**Comment by mhmmd-ysf** [comment]
[Same Issue](https://github.com/vercel/next.js/issues/10061#issuecomment-1546736494)

> Same issue, same resolution.

But in my case there are 3 instances? (2 nodes and 1 from Google)

Is it supposed to be like this?

**Comment by nagarro-subham** [comment]
Faced same issue but it started working fine as soon as i upgraded the node version 16.8 to latest.

**Comment by Amirbarzegari** [comment]
> I had a similar problem, for me it was because I accidentally had created an asynchronous client component (switched from a server component and forgot to make it synchronous.) I didn’t get any error messages, just a loading page so it was a bit tricky to debug.

Thank you so much, was dealing with this bug for a weak. I think Next js should include a warning/error of some sort and close this issue.

**Comment by timothy-okoduwa** [comment]
i was having similar issue and i must say upgrading my node version to 18 didn't work, i even cleared cache still nothing what worked for me was renaming that component that was not responding to changes. My issue was coming from my signup component (i created a componet outside and passed it in my page.js

`import React from 'react';
import Signin from '../components/Signin';

const page = () => {
  return (
    <div>
      <Signin />
    </div>
  );
};

export default page;
`

what i did was to change the name of the component (the Signin component was formally name Login) to the same name that the folder that acts as the route is bearing (which is  Signin)

**Comment by Mjeyz** [comment]
Changing dev port from 3000 to 3001 resolved my issue, so you should try as well

**Comment by SahilAggarwalHeliverse** [comment]
The point about Typescript, you are correct!
I faced the same issue recently where next.js was logging complied successfully but infinitely loading the webpage. I never imagined this could be because of Typescript. I actually created a custom type and using it in multiple files by exporting it from a file. Now, I am still figuring out why exactly is next.js showing this behaviour with custom types.
Did you find any clue?

**Comment by jobizzness** [comment]
@SahilAggarwalHeliverse you are on point. seems like ts is the issue here. removed custom types and it started working fine.

**Comment by patilanz** [comment]
same problem. Next compiles but no response is send to the browser.

I tried deleting .next node_modules, changing the port, updating node and next. Nothing helped. There should be a way to debug this

**Comment by dayoolacodes** [comment]
> For anyone struggling with this in 2023. Updating node to v18 solved the problem for me on Mac Pro m1 / Ventura

Thanks so much for this. This finally worked. This is the worst kind of error you want to have. There's no clue on the console or error thrown

**Comment by borg** [comment]
One page stuck. It's using <Script> to load a canvas js library. Loads fine for a while, then stops and no console logs showing at all...and no error logs. 

Changed <Script> method from onLoad to onReady and that seems to work. Why server invokes onLoad only for a while I don't know. Maybe helps someone.


`"next": "13.5.4"`

**Comment by leerob** [comment]
👋  Hey folks. Wanted to summarize this issue.

Some of you all are experiencing an issue where the Next.js development server gets stuck after a period of time, causing requests to fail or time out. It's tricky because the problem seems to occur intermittently and isn't clearly tied to any particular change or action. There's been reports across different operating systems _and_ versions of Next.js. 

Solutions / workarounds suggested throughout this issue:

1. Running the app with just Next.js `next dev` instead of `vercel dev` (we recommend doing this regardless)
2. Changing the port from the default `3000` to something else (e.g., running `next dev -p 1234`)
3. Clearing the cache, including service workers
4. Upgrading Node.js to version 18 or later
5. Deleting the `.next` folder and `node_modules` and then rebuilding the project
6. Having two instances of Next.js running simultaneously, terminating the extra process resolved the issue

Note that not everyone has been able to resolve the issue, and there isn't a one-size-fits-all solution that works in all cases. I encourage everyone to keep sharing their experiences and any potential fixes they come across. And if you are still seeing an issue and can consistently reproduce, please post that reproduction so we can investigate. Thanks!

**Comment by SebHex** [comment]
> Solutions / workarounds suggested throughout this issue:
> 
> 1. Running the app with just Next.js `next dev` instead of `vercel dev` (we recommend doing this regardless)
> 2. Changing the port from the default `3000` to something else (e.g., running `next dev -p 1234`)
> 3. Clearing the cache, including service workers
> 4. Upgrading Node.js to version 18 or later
> 5. Deleting the `.next` folder and `node_modules` and then rebuilding the project
> 6. Having two instances of Next.js running simultaneously, terminating the extra process resolved the issue

I've had this issue multiple times, usually solution 5 works for me.

Here's some solutions that worked for me on the occasions when solution 5 didn't:

1. **Resetting my PC**
2. **Upgrading Node.js**
 In my case, I upgraded from from v20.3.1 to v20.9.0)
3. **Clearing service workers**
 When using [next-pwa](https://ducanh-next-pwa.vercel.app/), the service worker left over from my build server was causing an issue on my dev server. To prevent this issue reoccurring, I now run my dev and build on different ports. For example, my `start` script, is now `next start -p 3001`

**Comment by prunusnira** [comment]
what about having same issue on production mode too?
should i make a way to force refresh the page?

**Comment by samcx** [comment]
Hi everyone!

I will be moving this issue to our <picture data-single-emoji=":nextjs:" title=":nextjs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs/2a85d633ae594556.png" alt=":nextjs:" align="absmiddle"></picture> [Discussions](https://github.com/vercel/next.js/discussions) because, as [mentioned before](https://github.com/vercel/next.js/issues/10061#issuecomment-1793886006), it seems a variety of ways can cause this issue to arise.

We still encourage folks to [file bugs](https://github.com/vercel/next.js/issues/new/choose) outside of this thread detailing the exact issue, with a <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> and details for how to consistently reproduce the issue!

Happy 2024!
