### ISSUE TITLE
Tree shaking doesn't work with Typescript barrel files

### ISSUE THREAD

**Issue by majelbstoat** [zeit/next.js#12557]
# Bug report

I originally raised this as a [discussion](https://github.com/zeit/next.js/discussions/11773), but now I think it's a bug.

## Describe the bug

When using a [barrel file](https://dev.to/luispa/how-to-create-barrels-in-typescript-or-javascript-59ma) to re-export components from a single location, tree-shaking does not function correctly. 

## To Reproduce

I'm using Next 9.3.6 and I've arranged my components like:

```tsx
  components/
    Header/
      Header.tsx
    Sidebar/
      Sidebar.tsx
    index.ts
```

where index.ts is a barrel file that re-exports from each individual component file:

```tsx 
  export * from './Header/Header.tsx'
  export * from './Sidebar/Sidebar.tsx'
  // ...
```

I then use a couple of components in _app.tsx like:

```tsx
import { Header, Sidebar } from "../components"
```

There's about 100 components defined, and only a couple are used in _app.tsx. But when I analyze the bundle I have a very large chunk, shared by all pages, and it contains all my components, resulting in an inflated app page size:

<img width="748" alt="Screenshot 2020-05-06 09 35 32" src="https://user-images.githubusercontent.com/425787/81183292-f8bbdf00-8f7c-11ea-91c9-4b95adff907a.png">

I use a similar import strategy within pages, and every one of them appears to contain every component.

my tsconfig.json is:

```json
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": ".",
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "preserveConstEnums": true,
    "removeComments": false,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es5"
  }
```

and I'm using next's native support for the baseUrl field. I haven't changed the module or the target.

When I change the _app.tsx imports to:

```tsx
import { Header } from "../components/Header/Header"
import { Sidebar } from "../components/Sidebar/Sidebar"
```

the common bundle and app page size drops dramatically, as I would expect it to:

<img width="751" alt="Screenshot 2020-05-06 09 34 21" src="https://user-images.githubusercontent.com/425787/81183384-1be68e80-8f7d-11ea-9aed-e32a1d871ab9.png">

## Expected behavior

The app page size should be the same using both import strategies.

## System information

- OS: [e.g. macOS]
- Version of Typescript: [e.g. 3.8.3]
- Version of Next.js: [e.g. 9.3.6]

**Comment by timneutkens** [comment]
Feel free to investigate and solve

**Comment by rahul3103** [comment]
https://github.com/vercel/next.js/discussions/13490

Same happening with jsx also.

**Comment by seeekr** [comment]
Has anyone been able to solve this? In one of our projects we seem to be getting no tree shaking at all for any TS application code, only for third party library code.

Alternatively, could any of the maintainers provide some hints as to how one would best go about investigating and solving such an issue?

**Comment by stevethatcodes** [comment]
> Has anyone been able to solve this? In one of our projects we seem to be getting no tree shaking at all for any TS application code, only for third party library code.
> 
> Alternatively, could any of the maintainers provide some hints as to how one would best go about investigating and solving such an issue?

@seeekr We actually ended up just removing our barrel files.

I did a simple experiment with Webpack and a couple of JavaScript modules + a barrel file (no Next, or Typescript) and the same behaviour was present with limited options to enable tree shaking to occur. 

If you have no side effects in your code then you may be able to look into the [Webpack side effects](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) setting to allow this to work for you, but as soon as you're importing a module classed as a side effect, you may start to notice issues. For us, our polyfill imports stopped working along with a whole host of other stuff.

I'm not sure this is something Next can/should solve though, as it seems to be inherent to Webpack

**Comment by VWSCoronaDashboard8** [comment]
@stevethatcodes It seems to work for me as long as I specify side effects in package.json:

```json
"sideEffects": [
    "./src/some-side-effectful-file.js"
  ]
```

**Comment by stevethatcodes** [comment]
@VWSCoronaDashboard8 Yeah, that's an approach we tried, though still had issues with the polyfills not loading. In fairness, we took the approach to remove barrel files as the path of least resistance, as they didn't add much value and we didn't need to do anything else to our Next/Webpack setup to bring back tree-shaking.

**Comment by sphilee** [comment]
With webpack 5, tree shaking seems to work.
https://webpack.js.org/blog/2020-10-10-webpack-5-release/#major-changes-optimization

**Comment by RobbyUitbeijerse** [comment]
@sphilee I don't actually think it works / resolves the issue, I've installed Webpack 5 on my current Next.js projects but it doesn't have any positive impact on the bundle size, at least for barrel files structured as the issue example by @majelbstoat.

**Comment by VWSCoronaDashboard8** [comment]
@RobbyUitbeijerse @sphilee I have concluded the same. Webpack 5 didn't solve this issue for me.

**Comment by RobbyUitbeijerse** [comment]
Based on the following issue https://github.com/webpack/webpack/issues/11821 , Webpack 5 should actually eliminate dead code with the minimize option being enabled (which is the case by default for `next build`). Let's assume that it does (I haven't actually verified it myself) - 

What I'm concerned about is that it might actually work for the shared bundle which is loaded for all pages, but doesn't actually consider the page by page chunks, meaning that while dead code is actually eliminated from the shared bundle - you are still left with a single bundle containing everything except for smaller chunks per page that only contain what you need for that page. Quite unsure whenever it's possible to actually resolve that or that changing the imports is the only way to go.

**Comment by RobbyUitbeijerse** [comment]
@timneutkens Webpack is not my strong suit, but do you have any clue if my comment above makes any sense in terms of what we are seeing?

**Comment by kelvinlouis** [comment]
I had similar issues in the past when using `export * from 'xxx`. Have you tried explicitly re-exporting your named and default exports in the barrel files?

In the past we also had [issues with babel when it came to exporting types](https://github.com/babel/babel/issues/8361). Since then we started exporting types explicitly using `export type`.

```
// index.ts
export {
  default as Header,
  HeaderX,
  HeaderY,
} from './Header/Header.tsx';

export type {
  Props as HeaderProps,
  AdditionalHeaderTypeX,
} from './Header/Header.tsx';

export {
  default as Sidebar,
  SidebarX,
  SidebarY,
} from './Sidebar/Sidebar.tsx';

export type {
  Props as SidebarProps,
  AdditionalSidebarTypeX,
} from './Sidebar/Sidebar.tsx';
```

**Comment by RobbyUitbeijerse** [comment]
I actually started doing the same recently:

![image](https://user-images.githubusercontent.com/10176709/106746953-89fed580-6623-11eb-862d-a1f2e84d75a0.png)

But it turns out, no luck:

![image](https://user-images.githubusercontent.com/10176709/106746991-97b45b00-6623-11eb-9e11-f9d878981b45.png)


What I did find tho, that when I put all of the components in an external library and build that library using Rollup while preserving the modules, tree shaking of the same components seems to work properly, meaning that it should be possible to get it all working one way or the other.

**Comment by nandorojo** [comment]
> I actually started doing the same recently:
> 
> ![image](https://user-images.githubusercontent.com/10176709/106746953-89fed580-6623-11eb-862d-a1f2e84d75a0.png)

Same experience here. I was pulling my hair out trying to figure out on this. I have a monorepo, and in the `index.ts` of each package, I was re-exporting my components. Not only did this break tree shaking: it also made `yarn next dev` take like a minute longer to load. Changing my imports directly to the root file of the components solved this. Wish I'd known this sooner – I have a lot of imports to change.

I can make a repro in a monorepo this weekend.

**Comment by R-Bower** [comment]
I've been pulling my hair out trying to find a fix for this.  I managed to get this working for my TSX monorepo by adding `"sideEffects": false` to the component library's `package.json`.

**Comment by R-Bower** [comment]
@JoeyFenny 
I managed to get this working by setting `"sideEffects": false` in the package.json of the package with the barrel export.  Also may want to check this comment: https://github.com/vercel/next.js/issues/12557#issuecomment-696749484

**Comment by jrmyio** [comment]
I am running into simular problems in a non next.js project. Upgrading from webpack 4 to webpack 5 did not fix it, sideEffects: "false" in the package.json does enable tree shaking but the barrel pattern still fails.

I think this is a webpack problem, maybe we should move the dicussion there? 
Though it would really help if we got a minor example repository that shows the problem.

**Comment by JoeyFenny** [comment]
settings sideEffects to false and adding `/*#__PURE__*/` to the function call did not work either. But I agree that this discussion should perhaps be moved to webpack

**Comment by b2rsp** [comment]
We dont have any news or ideas about this? I am really struggling to fix this since its having a big impact in our page load.

**Comment by sokra** [comment]
For tree-shaking to work with a barrel file you need

* flag the file and/or the child files as side effect free (`"sideEffects": false` in package.json)
* use webpack 5 OR build in production mode in webpack 4
* not bundle the library (it must be in separate files for sideEffects to work
* Alternatively to side effect free flagging you can use `/*#__PURE__*/` to carefully flag statements that might be considered as having side effects. If you do that, you must minimize to file to see the effect. This is very tricky to get right

**Comment by nandorojo** [comment]
> not bundle the library (it must be in separate files for sideEffects to work

@sokra I want to have barrel files as the `main` file for each of my monorepo's packages. If I am adding these monorepo packages to `next-transpile-modules`, would that constitute "bundling" the library?

**Comment by sokra** [comment]
> > not bundle the library (it must be in separate files for sideEffects to work
> 
> @sokra I want to have barrel files as the `main` file for each of my monorepo's packages. If I am adding these monorepo packages to `next-transpile-modules`, would that constitute "bundling" the library?

no. I was talking about double bundling, so using a pre-bundled library.

**Comment by dsacramone** [comment]
Apologize if this has already been gone over, but experiencing this with my react-component library, which uses a barrel file. Using rollupjs, and importing this component library into my NextJS app -- and its not tree shaking. Even with sideEffects set properly. ...... anyone using their react-component library effectively in a NextJS app that tree shakes?

**Comment by feluna** [comment]
I was using rollup to bundle a library as well, also with a barrel file. It wasn't tree shaking, it also put server-side code into client bundle, like the modules i m using inside getStaticProps etc.. 

If u do not bundle the library, and literally just copy the source code into your package, and use next-transpile modules with it, it does tree-shake.

Currently, i couldnt find a better solution, all other options are creating page files with larger size.

````
const withTM = require("next-transpile-modules")(["your-library"]);

const config = {
  // ... your config
};

module.exports = withTM(config);
````

**Comment by yuchant** [comment]
```
 webpack: (config, { dev }) => {
        config.module.rules = [
            ...config.module.rules,
            // ensure our libs barrel files don't constitute imports
            {
                test: /libs\/.*src\/index.ts/i,
                sideEffects: false,
            },
        ]
```

**Comment by furkanonbasilar** [comment]
Is there any news about that?

**Comment by alessandrojcm** [comment]
> Disabling side effects for my imported barrel libs works for me.
> 
> I don't use side effects, seems like a lib thing to rely on that. Unless i'm sorely mistaken about side effects.
> 
> ```
>  webpack: (config, { dev }) => {
>         config.module.rules = [
>             ...config.module.rules,
>             // ensure our libs barrel files don't constitute imports
>             {
>                 test: /libs\/.*src\/index.ts/i,
>                 sideEffects: false,
>             },
>         ]
> ```

This just trimmed 200kb off my bundled, thanks a million.

**Comment by mfv-brian** [comment]
> 

yessss,
trimmed 200kb from my bundled too, thanks mates

**Comment by daphnesmit** [comment]
is that webpack config put in nextjs... because if you have a node_modules thats bundles and doesnt treeshake how does that pointer to libs/src/index.ts help?

**Comment by yuchant** [comment]
> is that webpack config put in nextjs... because if you have a node_modules thats bundles and doesnt treeshake how does that pointer to libs/src/index.ts help?

This issue isn't about tree shaking `node_modules`, it's about tree shaking barrel imports from your own packages.

**Comment by aboqasem** [comment]
Tree-shaking barrel files could lead to possibly different behavior in development and production. Since imported files can have side effects that would be introduced in development but not in the tree-shaken version.

Since [side effects are not identifiable at the moment](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free), maybe introduce an easier way to mark the file as side-effect-free?

For example in a barrel file:
```
// @ignore-side-effects
```

Or in each of the files:
```
// @side-effects: false
```

Or something similar.

**Comment by Slowl** [comment]
Happy 2 years to this issue 🥳

I'm still facing this issue in my project when using barrel files coupled with the tsconfig path option.
I have a folder `components`, which has subfolders like `sections`, and each of these folders have an index.ts file presented like this

```ts
import SectionCarousel from './SectionCarousel'
import SectionDemo from './SectionDemo'
import SectionInfiniteCarousel from './SectionInfiniteCarousel'
import SectionIntro from './SectionIntro'

export {
	SectionCarousel,
	SectionDemo,
	SectionInfiniteCarousel,
	SectionIntro,
}
```

And then I'm using my components like this : 
```ts 
import { SectionCarousel, SectionDemo, SectionInfiniteCarousel, SectionIntro } from '@/components/sections'
```

I've been trying everything for 2 weeks now and I can't find a solution without rewriting all of my imports in every components and pages, which I obviously can't do right now.
It's a ticking bomb, since every new line of code I write, is being sent to every pages

**Comment by tomerzcod7** [comment]
> Disabling side effects for my imported barrel libs works for me.
> 
> I don't use side effects, seems like a lib thing to rely on that. Unless i'm sorely mistaken about side effects.
> 
> ```
>  webpack: (config, { dev }) => {
>         config.module.rules = [
>             ...config.module.rules,
>             // ensure our libs barrel files don't constitute imports
>             {
>                 test: /libs\/.*src\/index.ts/i,
>                 sideEffects: false,
>             },
>         ]
> ```

Can this solution be altered to treeshake node_module libraries? I've been trying to use it for a components library I'm using (which is built for es modules and has sideEffects marked as false) without any luck

**Comment by pipech** [comment]
> Disabling side effects for my imported barrel libs works for me.
> 
> I don't use side effects, seems like a lib thing to rely on that. Unless i'm sorely mistaken about side effects.
> 
> ```
>  webpack: (config, { dev }) => {
>         config.module.rules = [
>             ...config.module.rules,
>             // ensure our libs barrel files don't constitute imports
>             {
>                 test: /libs\/.*src\/index.ts/i,
>                 sideEffects: false,
>             },
>         ]
> ```

This does works, I'm able to trim down ~200kb from my bundle.
But let me elaborate a bit for anyone who might not get it at first glance like myself.

For example this is your project structure.
```
├── ...
├── src
│   ├── pages
│          ├─ index.tsx
│          └─ somepage.tsx
│   └── components
│          ├─ index.ts
│          ├─ ComponentA.tsx
│          └─ ComponentB.tsx
│   └── ...
├── package.json
└── next.config.js
```

What you want to do is in your `next.config.js` add this webpack config.
Inside test list you can add regex path to your barrel file.

This will tell webpack that this file is side-effect free, please go ahead and tree-shake this thing.

```
      webpack(c) {
        c.module.rules.push({
          test: [
            /src\/components\/index.ts/i,
          ],
          sideEffects: false,
        });

        return c;
      },
```

That it's, hope this helps. 😁

**Comment by Sodj** [comment]
@pipech 
This sounds promising, 
do I have to add the path of each `index.ts` file?
or would this work `/src\/.*index.ts/i` ?

**Comment by joe-bell** [comment]
Just chiming in to say that **adding `"sideEffects": false` to my app's `package.json`** solved this issue for me

(for `next@12.2.*`)

**Comment by Sodj** [comment]
Adding `sideEffects: false` did improve build final size, but the server side render on localhost is still super slow

**Comment by pipech** [comment]
I did try adding `sideEffects: false` to `package.json` but some how it broke the ui on my apps, not sure what happen there.

@Sodj I think you should play around with it a bit, but for my case it should only point to file that is barrel file index when regex touch anything else it broke the ui. Not sure if it because my poor code standard. 😅

**Comment by Sodj** [comment]
> @Sodj I think you should play around with it a bit, but for my case it should only point to file that is barrel file index when regex touch anything else it broke the ui. Not sure if it because my poor code standard. 😅

@pipech I have a lot of barrel files, I tried putting the regex in webpackconfig like suggested above but it didn't work

**Comment by zomars** [comment]
@Sodj 

> Also, for some reason, the prototypes I added to the Array object stopped working

Adding to the Array prototype IS [considered a side effect](https://sgom.es/posts/2020-06-15-everything-you-never-wanted-to-know-about-side-effects/), you should not tree shake that if needed globally.

**Comment by Sodj** [comment]
@zomars was able to add a regex that works for me ... thanks

**Comment by n-glaz** [comment]
Am unbarreling my barrels now after finding this, am disappointed that so much complexity has to be added to get barrels to work in NextJS... does anyone have a simple alternative indexing method besides breaking components into libraries separate from the repo being bundled?

**Comment by Sh1d0w** [comment]
I am using nx with webpack 5 and tree shaking works just fine. You can create libraries in the workspace and export them from single barrel index file and import them on other places.

**Comment by n-glaz** [comment]
I am relieved to hear this @Sh1d0w and will have a look to see if this is true

**Comment by bruceharrison1984** [comment]
Still not working for me. I had to add `"sideEffects": false` to package json. It reduced all my pages by 50% or more.

**Comment by ricardo-rp** [comment]
I am curious as to why people use barrel files. I feel like it's just adding an extra file that has a non-informational name to your project, and often complicates keyboard navigation (open definition, find file). The big advantage is making imports prettier? Which I spend basically zero time looking at.

Is there a benefit I'm missing on this or is it really about reducing lines of code in the import block?

**Comment by yuchant** [comment]
> I am curious as to why people use barrel files. I feel like it's just adding an extra file that has a non-informational name to your project, and often complicates keyboard navigation (open definition, find file). The big advantage is making imports prettier? I spend very little time looking at imports.
> 
> Is there a benefit I'm missing on this or is it really about reducing lines of code in the import block?

Barrel files are effectively an API. A specific interface that distinguishes private vs public code. It especially makes sense in a monorepo with local packages. The same concept (why do packages have a specific import interface) pros/cons applies to monorepo packages.  Being in the package mindset is helpful in its own right re; reusability/scalability too.
 
My opinion: barrels are annoying (having to create them, maintain them, deal with circular imports), but denoting public vs private code is helpful in maintenance just like `private` and `public` class methods.

Less refactoring required when files change; only the "API" (barrel file) needs to be updated. 

Hides implementation from consumers. 

Clear what changes are necessary if anything in public API changes, or if nothing in public API changes.

Arbitrary files imported by arbitrary other files is harder to maintain and understand than a single barrel. The possible scope of any modification is larger without barrels.

Ultimately, we all use barrels, via libraries. The same reasoning "why do libraries not just expose all file paths" applies to our own code as well.

There are cons, but that's not your question. Those are just my 2cents that come to mind right now.

**Comment by ricardo-rp** [comment]
@yuchant Very good explanation! Thank you.
So it seems it's actually very worth it to use barrels **mindfully**, generally when you're dealing with blocks of code that will be used in conjunction and want a sort of unified API.

If you don't use barrels by default, and only where it makes sense, it seems like a good enough solution would be to have a way to mark files as side-effect free.

**Comment by gtempesta** [comment]
> Disabling side effects for my imported barrel libs works for me.
> 
> I don't use side effects, seems like a lib thing to rely on that. Unless i'm sorely mistaken about side effects.
> 
> ```
>  webpack: (config, { dev }) => {
>         config.module.rules = [
>             ...config.module.rules,
>             // ensure our libs barrel files don't constitute imports
>             {
>                 test: /libs\/.*src\/index.ts/i,
>                 sideEffects: false,
>             },
>         ]
> ```

This worked also in my case! I'm not working with **Next.js** but with an ejected **Create React App**.
In case someone else needs it, here is the solution for a raw **Webpack** configuration.

```js
{
  module: {
    rules: [
      // other rules...
      {
        test: [/src\/common\/index.ts/i, /src\/hooks\/index.ts/i],
        sideEffects: false,
      }
    ]
  }
}
```
Also thanks @yuchant for the detailed explanation on **barrel files**!
I've quoted a part of it in the answer I gave to my own question on this subject in Stack Overwlow, let me know if this is something you don't and I will remove it!
https://stackoverflow.com/questions/74442696/webpack-doesnt-split-a-huge-vendor-file-when-modules-are-exported-and-imported

**Comment by sandmule** [comment]
If you are using a monorepo with a component library and are still having problems, you can try 
```
  webpack(config) {
    config.module.rules.push({
      test: /index\.(js|mjs|jsx|ts|tsx)$/,
      include: (mPath) => mPath.includes('component-library/src'),
      sideEffects: false,
    });

    return config;
  },
```

n.b. you can change `mPath.includes('component-library/src')` to a glob to capture multiple folders/files etc.

You can also place a `console.log(mPath)` to print out the exact file paths, if you have any confusion of the location of your files relative to next.

**Comment by septem1997** [comment]
Has anyone tried  [modularizeImports](https://nextjs.org/docs/advanced-features/compiler#modularize-imports) ?

**Comment by cseas** [comment]
This has become a bigger issue with the introduction of App directory. 

In the `pages` directory (or client components under `app`), importing from barrel files works. It won't tree shake anything but at least the build is successful.

With server components, if we import a component from an npm package, and even a single export of that library uses a client-side hook like `useState`, Next.js will throw an error for all imports from the barrel file of that npm package.

This means the only way right now to use imports from component libraries in a server component is to ask library authors to provide deep imports to the component files just for Next.js. We could alternatively mark the whole app as client rendered with `"use client"` but that defeats the purpose of using the `app` directory.

Feedback with a reproduction reported here: https://github.com/vercel/next.js/discussions/41745#discussioncomment-4884625

**Comment by JEGardner** [comment]
I have spent days trying basically everything I can think of to get Tree Shaking to work with the app router and barrel files, including all the suggested answers here, and have hit a dead end.

Half my pages use the Pages Router, and half use the App Router. The Pages Router pages seem to perform tree shaking on the barrel files properly, but the App Router pages are all double the kB of the Pages Router pages as soon as I import a single component.

Here's what I've tried so far:

- Moved all components into another package in my monorepo, and added `sideEffects: false` to that package.
- Many variations of editing the webpack config rules with `sideEffects: false`, both when the components were in the same package and in the new package. Interestingly, adding `sideEffects: true` doubles the size of the Pages Router pages, but the App Router pages stay the same.
- Many attempts with both Babel and SWC
- I think I am unable to use  [modularizeImports](https://nextjs.org/docs/advanced-features/compiler#modularize-imports) as I split my components into feature folders with a few layers of barrel files.

The only thing that works is bypassing the barrel files and importing components one by one... but I love barrel files and this seems like a (very time-consuming) step backwards. I think [Babel Direct Import Plugin](https://github.com/avocadowastaken/babel-plugin-direct-import) may have worked, but I couldn't get it to work.


I am pretty amazed that it doesn't just work out of the box as it seems like such a common thing to do and the whole point of NextJS is things are supposed to work out of the box.

**Comment by JEGardner** [comment]
An update on the above: I couldn't wait for a fix so I spent a day refactoring out my beloved barrel files so all my files now have tons of separate imports. My App Router routes dropped from ~640kB to ~80kB first load JS.

**Comment by dannyk08** [comment]
> An update on the above: I couldn't wait for a fix so I spent a day refactoring out my beloved barrel files so all my files now have tons of separate imports. My App Router routes dropped from ~640kB to ~80kB first load JS.

@JEGardner would it be possible to point the rest of us mortals on how to optimize these bundles? I'm at a loss on how to optimize my `@aws-amplify` and `@shopify/polaris` imports 

Thank you 🙏🏽

**Comment by enchorb** [comment]
+1 here, using a `Nx` monorepo and no tree-shaking is being down on the app router for custom libraries

**Comment by Rafi993** [comment]
> > An update on the above: I couldn't wait for a fix so I spent a day refactoring out my beloved barrel files so all my files now have tons of separate imports. My App Router routes dropped from ~640kB to ~80kB first load JS.
> 
> @JEGardner would it be possible to point the rest of us mortals on how to optimize these bundles? I'm at a loss on how to optimize my `@aws-amplify` and `@shopify/polaris` imports
> 
> Thank you 🙏🏽

+1

**Comment by cseas** [comment]
Is this issue now fixed with [Optimized Package Imports](https://nextjs.org/blog/next-13-5#optimized-package-imports)?

**Comment by william-fargues** [comment]
I'm sorry but I can't believe that this issue has been opened for more than 3 years now and that there is still no solution 🤷‍♂️

**Comment by JEGardner** [comment]
> I'm sorry but I can't believe that this issue has been opened for more than 3 years now and that there is still no solution 🤷‍♂️

I have to agree. All these micro-optimisations and then you have this which would probably save 100s of kb being sent on every route on most nextjs apps. Don't get it.

**Comment by enchorb** [comment]
@leerob - any ETA on a solution for this?

**Comment by Slowl** [comment]
I'm so happy I decided to make the changes early even if it took me some time to do it. It would have taken me more time today.

Crazy to see this is still not resolved.

Next step might be to move the project to Astro 🤔

**Comment by gajus** [comment]
Randomly stumbled upon this, but I highly recommend to every ESLint rule that restricts use of barrel files https://github.com/gajus/eslint-plugin-canonical#no-barrel-import

**Comment by robert-orlinski** [comment]
Hmm, either something was fixed or I don't understand.

I have set up very simple Next.js app using `create-next-app` (using Next 13.5.6 with pages directory) and created 5 files:

First file (`/components/OneComp.tsx`):

```tsx
export const OneComp = () => {
  console.log('first');

  return <div>OneComp</div>
}
```

Second file (`/components/CoupleComp.tsx`):

```tsx
export const Comp1 = () => {
  console.log('fst');

  return <div>OneComp</div>
}

export const Comp2 = () => {
  console.log('sec');

  return <div>OneComp</div>
}

export const Comp3 = () => {
  console.log('thrd');

  return <div>OneComp</div>
}
```

Third file (`/components/Sub/SubComp.tsx`):

```tsx
export const SubComp = () => {
  console.log('sub');

  return <div>OneComp</div>
}
```

Nested barrel file (`/components/Sub/index.ts`):

```ts
export * from './SubComp'
```

And the last one - main barrel file (`/components/index.ts`):

```ts
export * from './CoupleComp'
export * from './OneComp'
export * from './Sub'
```

It looks like this in the end:

<img width="183" alt="image" src="https://github.com/vercel/next.js/assets/25187173/6c570a54-7747-483b-85a7-63b268a76c60">

---

Then I have imported and used 2 from 5 components imported from the main barrel file into `_app.tsx` file (similar scenario to the one provided by the author on the whole thread):

```tsx
import { OneComp, Comp3 } from '@/components'
import '@/styles/globals.css'
import type { AppProps } from 'next/app'

export default function App() {
  return (
    <>
      <OneComp />
      <Comp3 />
    </>
  )
}
```

...and the end file generated after running `npm run build` and then `npm start` contains **ONLY** imported component's code. 

This is the content of generated `/_next/static/chunks/pages/_app-cfb55d8006062ffe.js` file:

```js
(self.webpackChunk_N_E=self.webpackChunk_N_E||[]).push([[888],{6840:function(n,e,_){(window.__NEXT_P=window.__NEXT_P||[]).push(["/_app",function(){return _(3564)}])},3564:function(n,e,_){"use strict";_.r(e),_.d(e,{default:function(){return App}});var c=_(5893);let Comp3=()=>(console.log("thrd"),(0,c.jsx)("div",{children:"OneComp"})),OneComp=()=>(console.log("first"),(0,c.jsx)("div",{children:"OneComp"}));function App(n){let{Component:e,pageProps:_}=n;return(0,c.jsxs)(c.Fragment,{children:[(0,c.jsx)(OneComp,{}),(0,c.jsx)(Comp3,{})]})}_(415)},415:function(){}},function(n){var __webpack_exec__=function(e){return n(n.s=e)};n.O(0,[774,179],function(){return __webpack_exec__(6840),__webpack_exec__(9974)}),_N_E=n.O()}]);
```

As you can see, it only contains code of `OneComp` and `Comp3` which were imported. You can easily double check that by searching for `console.log` instances.

Anticipating questions: only this file contains code related to components created by me.

Is there something I don't understand here or what I see here is tree shaking in action? 🤔

**Comment by r34son** [comment]
> Is this issue now fixed with [Optimized Package Imports](https://nextjs.org/blog/next-13-5#optimized-package-imports)? #54695

Yeah, seems like it helps. I`ve tested with @nextui-org/react and many of internal packages was gone

**Comment by jorenbroekema** [comment]
For those who have hypothesized that it's a Webpack issue, I cannot reproduce the issue in Webpack alone, treeshaking barrel files seems to work fine there: https://replit.com/@JorenBroekema/barrel-treeshaking

So seems like a NextJS specific problem.

**Comment by samcx** [comment]
Hi everyone!

Please let us know if https://nextjs.org/docs/app/api-reference/next-config-js/optimizePackageImports resolves your issue with regards to proper tree shaking with Typescript barrel files. If yes, we will proceed with moving this issue to <picture data-single-emoji=":nextjs:" title=":nextjs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs/2a85d633ae594556.png" alt=":nextjs:" align="absmiddle"></picture> [Discussions](https://github.com/vercel/next.js/discussions).

Happy 2024!

**Comment by ivan-kleshnin** [comment]
> Please let us know if https://nextjs.org/docs/app/api-reference/next-config-js/optimizePackageImports resolves your issue with regards to proper tree shaking with Typescript barrel files. If yes, we will proceed with moving this issue to  [Discussions](https://github.com/vercel/next.js/discussions).

The very idea that we have to manually list libraries that were previously tree-shaken automatically is... not inspiring.

**Comment by samcx** [comment]
@ivan-kleshnin Can you share a <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> showcasing where it was done automatically so we can take a closer look?

**Comment by gajus** [comment]
@ivan-kleshnin out of curiosity, why did you thumbs down ESLint plugin I suggested?

https://github.com/vercel/next.js/issues/12557#issuecomment-1754370032

It is working great for us

**Comment by jorenbroekema** [comment]
Regardless of whether it was or wasn't done automatically previously, can you explain why it makes sense to manually specify a list of package to optimize? Isn't it always a good default to optimize dependencies? From the docs, it is not clear in what scenario it is helpful to "not optimize packages".

From what I can tell, the default should be to optimize/treeshake all dependencies, at least for production, with perhaps an opt-out, although I don't see a reason for that either. Again, maybe I'm missing some context but this seems to me like really awful API design when considering the principle of "choose good defaults" and "allow users to opt into necessary exceptions".

**Comment by jorenbroekema** [comment]
> @ivan-kleshnin out of curiosity, why did you thumbs down ESLint plugin I suggested?
> 
> [#12557 (comment)](https://github.com/vercel/next.js/issues/12557#issuecomment-1754370032)
> 
> It is working great for us

I'm not the downvoter but couple of reasons:
1. You're linting plugin fixes barrel files, great, but that only helps for my dependencies exporting barrel files if I let ESLint lint my dependencies, and then it fixes my dependencies code which I'm not happy to commit to git, personally
2. A linting plugin as a solution to the problem that Next's default behavior with regards to treeshaking barrel files sucks is not really a good solution, it's a workaround. Maybe a useful one at that, but I get the downvote, I personally don't see it as an acceptable workaround as it introduces another devdependency -> arguably tech debt.

**Comment by ivan-kleshnin** [comment]
> @ivan-kleshnin out of curiosity, why did you thumbs down ESLint plugin I suggested?
> https://github.com/vercel/next.js/issues/12557#issuecomment-1754370032
> It is working great for us

Because your plugin "Restricts the use of barrel files". I don't see barrel files as something bad that should be avoided, moreover me and all my teams in the present/past heavily used them outside of NextJS context, with great success. They are convenient and I'm not aware of any cons, except that they break NextJS... So why I should lint myself against NextJS issue? 🤔

**Comment by IonelLupu** [comment]
I came across this issue when using [react-aria-components](https://react-spectrum.adobe.com/react-aria/). When using just a simple `<Button>`, the entire [react-aria-components](https://react-spectrum.adobe.com/react-aria/) library is imported.

While reading this thread, I saw this issue linked above: https://github.com/vercel/next.js/issues/44039

It seems when using `use client` in your page, makes the builder tree-shake correctly. Not sure why is that. Buuuut, the issues don't stop there. If you use the <Button> on page A and the <Select> on page B, the bundle analyzer shows page A imports the <Select> component EVEN if page A doesn't use the <Select> component. It seems it combines all of the react-aria-components files into one big import in EVERY SINGLE PAGE. 

I detailed the issue here: https://github.com/vercel/next.js/discussions/60206

**Comment by samcx** [comment]
> ...They are convenient, and I'm not aware of any cons

@ivan-kleshnin As far as I'm aware, there is a [cost to using barrel files](https://vercel.com/blog/how-we-optimized-package-imports-in-next-js#what's-the-problem-with-barrel-files), which is why we recently introduced `optimizePackageImports`.

I agree that it is not ideal to manually have to add packages to `optimizePackageImports` if the package in question is not already manually listed here → https://github.com/vercel/next.js/blob/12e888126ccf968193e7570a68db1bc35f90d52d/packages/next/src/server/config.ts#L710-L765.

Ideally, we just automatically detect packages that need to use `optimizePackageImports`, so the user doesn't have to even concern themselves with this. Will be discussing this <picture data-single-emoji=":nextjs:" title=":nextjs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs/2a85d633ae594556.png" alt=":nextjs:" align="absmiddle"></picture> team to see how we can achieve that!

**Comment by IonelLupu** [comment]
> > ...They are convenient, and I'm not aware of any cons
> 
> @ivan-kleshnin As far as I'm aware, there is a [cost to using barrel files](https://vercel.com/blog/how-we-optimized-package-imports-in-next-js#what's-the-problem-with-barrel-files), which is why we recently introduced `optimizePackageImports`.
> 
> I agree that it is not ideal to manually have to add packages to `optimizePackageImports` if the package in question is not already manually listed here. → https://github.com/vercel/next.js/blob/12e888126ccf968193e7570a68db1bc35f90d52d/packages/next/src/server/config.ts#L710-L765
> 
> Ideally, we just automatically detect packages that need to use `optimizePackageImports`, so the user doesn't have to even concern themselves with this. Will be discussing this with the team to see how we can achieve that!

@samcx optimizePackageImports doesn't work in my case when using react-aria-components. I detailed the issue in the comment above. Using Vite works correctly. Also, using "use client" kinds gives okish results, but there is a bigger problem when you have multiple pages. Again? Detailes in the discussion I listed above

**Comment by samcx** [comment]
@IonelLupu Thanks for re-iterating your issue involving react-aria-components and creating a detailed discussion post. I have created https://github.com/vercel/next.js/issues/60246 from your discussion post and will be taking a look!

**Comment by ivan-kleshnin** [comment]
> @ivan-kleshnin As far as I'm aware, there is a [cost to using barrel files](https://vercel.com/blog/how-we-optimized-package-imports-in-next-js#what's-the-problem-with-barrel-files), which is why we recently introduced optimizePackageImports.

As far as I can see, those paragraphs simply mention the issue with unoptimized imports – without tree-shaking... 
I don't see any details about some inherent cost of barrel files per se.

**Comment by samcx** [comment]
Update: there was a fix for the above issue that entailed importing direct Client Components in Server Components.

https://github.com/vercel/next.js/issues/60246#issuecomment-1954296431

**Comment by tocosastalo** [comment]
Maybe it's not related, but I came across this issue when using [plaiceholder](https://plaiceholder.co/docs), which is supported only in server components. 

I have barrel/index file which re-exports both server and client "elementary" components. During development when some page imports client component from the barrel file, the app crashes on error "ReferenceError: require is not defined". So it looks like the server component is automatically imported/loaded and gets into the browser despite the fact that it is marked as server component (without "use client" at the top) and is not used anywhere on the page.

Simplified components are:


```tsx
// ServerImageWithBlur.tsx
import { getPlaiceholder } from "plaiceholder"

export const ServerImageWithBlur = async (props: ImageProps) => {
  const { base64, img } = await getPlaiceholder(props.src)
  return <Image placeholder="blur" blurDataURL={base64} {...props} {...img} />
}
```

```tsx
// Navbar.tsx
"use client" 

export const Navbar = () => {
  return <div>...</div>
}
```


```ts
// index.ts
export { ServerImageWithBlur } from "./ServerImageWithBlur"
export { Navbar } from "./Navbar"
```

Error:
```
Unhandled Runtime Error
ReferenceError: require is not defined
```

When I comment the re-export of the server component from `index.ts`, the application works.

**Comment by samcx** [comment]
@tocosastalo Can you create a new separate issue so we can take a look?

In the meantime, I will be moving this over to Next.js [discussions](https://github.com/vercel/next.js/discussions), since we have veered from the original issue posted back in 2020.
