### ISSUE TITLE
Resolve Webpack deprecation warning for loaderUtils.parseQuery()

### ISSUE THREAD

**Issue by ads1018** [zeit/next.js#1387]
Seeing the following deprecation warning after updating to the latest version of Next beta. Can anyone else confirm?

```
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56 parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
````

**Comment by arunoda** [comment]
We fixed it. I hope it's coming from a other plugin using it.
Need to investigate.

**Comment by Mcebrera** [comment]
@arunoda noob here, what is the fix exactly? Can you link me to it?

**Comment by aranajhonny** [comment]
@arunoda The error comes from babel-loader@6.4.0  [#391](https://github.com/babel/babel-loader/pull/391). Already corrected but are still in alpha [v7.0.0-alpha.1](https://github.com/babel/babel-loader/releases)

**Comment by arunoda** [comment]
Thanks @aranajhonny .
Frankly, there's nothing we can about this until babel released v7.0.0

**Comment by aranajhonny** [comment]
Even though I install this version, and it still shows me the same warning. we will wait.

**Comment by trevordmiller** [comment]
I just upgraded to next.js 2 official and am still getting this error:

![image](https://cloud.githubusercontent.com/assets/5497885/24535208/e47aeab4-158f-11e7-9949-46d2aa5559a1.png)

I tried wiping and reinstalling `node_modules`, but no luck.

I am using yarn instead of npm if that matters.

**Comment by arunoda** [comment]
@trevordmiller this is not an error.
It's a warning emit by babel-loader.

It's fixed with babel-loader 7. But we can't use that because still it's beta.
