### ISSUE TITLE
Memory leak when refreshing during rebuild

### ISSUE THREAD

**Issue by nmaro** [zeit/next.js#1428]
Sometimes when I modify a file, and next.js is rebuilding, and then quickly move to the browser and refresh the page, the browser's memory quickly goes up until the computer freezes.

Browser: Firefox 52.0
Next version: next@2.0.0-beta.38

**Comment by timneutkens** [comment]
Like an infinite loop?

**Comment by nmaro** [comment]
Maybe, but a loop on its own wouldn't cause the browser to fill up the RAM. Interestingly enough it hasn't happened (yet) with chrome.

**Comment by arunoda** [comment]
@nmaro are you using the latest version of Next.
We recently removed our React patching code and that might a case for this.

**Comment by arunoda** [comment]
@nmaro I tried with our `Zeit.co` and with few other apps. I couldn't reproduce the issue.
May be it's because of one of the NPM module you use or something in your app.

Is it possible for you to isolate that?

**Comment by arunoda** [comment]
I'm gonna close this for now. Feel free to re-open with some ways to re-produce this.

**Comment by kunokdev** [comment]
I am using Next.js and sometimes I get infinite loop inside Firefox browser when I open developer tools. Version of  Nextjs is 2.4.0 and Firefox 53. Other than that, sometimes when I hard refresh page it tends to rebuild again, and once loaded, it rebuilds again, infinitively.

**Comment by pmualaba** [comment]
Same issue here: When using next.js with express custom server, and hard refreshing the page in the browser a few times creates an infinite refresh loop in the browser:
i use npm run dev with the following settings: 

package.json:
"scripts": {
     "dev": "NODE_ENV=development pm2 start node.config.js --no-daemon"
      ...

node.config.js : 
module.exports = {
    apps: [{
        name: 'server',
        script: './server.js',
        instances: 1,
        exec_mode: 'cluster',
        watch: ['packages/**/api/*'],
        ignore_watch: ['node_modules', '.temp', '.next', '.git']
    }]
}

**Comment by kunokdev** [comment]
Can this issue be reopened? I had to completely move to Chrome in order to develop in React.js. Anytime I try to open my project (dev mode only) in Firefox I get instant memory leak and must force reset. I never had any issues with Firefox before. Could we start examining the cause of this problem?

**Comment by angel200sdnot** [comment]
> I had to completely move to Chrome in order to develop in Next.js. Anytime I try to open my project (dev mode only) in Firefox I get instant memory overload and must force reset.
This has been happening to me but i can't remember on which version the problem started or if it hasnt been there since i started using Next on January

**Comment by arunoda** [comment]
Let's investigate this further.

**Comment by nathanqueija** [comment]
Same happening here.

**Comment by kunokdev** [comment]
@nathanqueija do you remember at which point did memory leak appear? Do you use any custom config? Can you share your package.json?

**Comment by thangngoc89** [comment]
I'm experiencing too often that this become to bother me.

Here is the dump 

```
<--- Last few GCs --->                
     
[16570:0x340a5a0] 10373222 ms: Mark-sweep 1387.6 (1469.8) -> 1387.5 (1469.3) MB, 641.4 / 0.1 ms  allocation failure GC in old space requested
[16570:0x340a5a0] 10374158 ms: Mark-sweep 1387.5 (1469.3) -> 1387.2 (1427.8) MB, 936.1 / 0.2 ms  last resort
[16570:0x340a5a0] 10374768 ms: Mark-sweep 1387.2 (1427.8) -> 1387.1 (1427.8) MB, 610.0 / 0.1 ms  last resort
                                                                     
                                                                     
<--- JS stacktrace --->                                              
       
==== JS stack trace =========================================        
                                                                     
Security context: 0x3813d7929891 <JS Object>   
    1: DoJoin(aka DoJoin) [native array.js:~96] [pc=0x247d5ddf6c85](this=0x18c20aa82311 <undefined>,p=0x3dab2e9ad69 <JS Array[2]>,q=2,E=0x18c20
aa823b1 <true>,A=0x18c20aa82471 <String[0]: >,z=0x18c20aa82421 <false>)
    2: Join(aka Join) [native array.js:~121] [pc=0x247d5d62cfa8](this=0x18c20aa82311 <undefined>,p=0x3dab2e9ad69 <JS Array[2]>,q=2,A=0x18c20aa8
2471 <String[0]: >,z=0x18c20aa82421 <fa...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out ofmemory
 1: node::Abort() [node]
 2: 0x13647ec [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Runtime_StringBuilderConcat(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0x247d5830437d
Aborted (core dumped)
error Command failed with exit code 134.
```

It usually happens every 1-2 hours in development mode. I know that tracing a memory leak is hard but any pointer where should I start to kill this bug would be appreciated

**Comment by nmaro** [comment]
As the op wanted to say that this is still happening to me, basically gave up on developing with firefox altogether. With chrome everything works fine for me.

**Comment by thangngoc89** [comment]
@nmaro oh so this issue is about memory leak in the browser? My issue is with the node process, and it happens no matter which browser I use (I develop on Chrome, Firefox)

**Comment by nmaro** [comment]
At least my issue, yes. I have to kill the browser in time or it blocks everything and have to restart my pc :)

**Comment by timneutkens** [comment]
I wonder if this might be related to a memory leak we fixed before related to calling `/static/` in your browser.

**Comment by chuyik** [comment]
Like @thangngoc89 said, this also happens every 1~2 hours in dev mode on my iMac.
I think it's not easy to provide a reproducible demo since it only happens on large project.
And I use Chrome 59/60, so it's probably related to the node process.

```
<--- Last few GCs --->

[92752:0x102801600]  2671867 ms: Mark-sweep 1382.1 (1452.2) -> 1382.1 (1452.2) MB, 390.9 / 0.0 ms  allocation failure GC in old space requested
[92752:0x102801600]  2672342 ms: Mark-sweep 1382.1 (1452.2) -> 1381.9 (1415.7) MB, 474.4 / 0.0 ms  last resort
[92752:0x102801600]  2672703 ms: Mark-sweep 1381.9 (1415.7) -> 1381.9 (1415.7) MB, 360.8 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2385f25266a1 <JS Object>
    1: DoJoin(aka DoJoin) [native array.js:~97] [pc=0x38fb59149422](this=0x25c1cbe02311 <undefined>,q=0x1a0c60fd0dc9 <JS Array[2]>,r=2,F=0x25c1cbe023b1 <true>,B=0x25c1cbe02471 <String[0]: >,A=0x25c1cbe02421 <false>)
    2: Join(aka Join) [native array.js:~122] [pc=0x38fb5910bf22](this=0x25c1cbe02311 <undefined>,q=0x1a0c60fd0dc9 <JS Array[2]>,r=2,B=0x25c1cbe02471 <String[0]: >,A=0x25c1cbe02421 <...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/edc/.nvm/versions/node/v7.10.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/edc/.nvm/versions/node/v7.10.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/edc/.nvm/versions/node/v7.10.0/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Users/edc/.nvm/versions/node/v7.10.0/bin/node]
 5: v8::internal::Runtime_StringBuilderConcat(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/edc/.nvm/versions/node/v7.10.0/bin/node]
 6: 0x38fb541843a7
got signal SIGABRT, exiting
```

**Comment by kunokdev** [comment]
@timneutkens can you link to that issue related to `./static` dir?
@nmaro @thangngoc89 do you use custom `.babelrc` file? can you share your package.JSON? are you using `nodemon` ?

**Comment by TAQ2** [comment]
I would also check what version of node you are on. That seemed to fix this exact issue for me. I moved from version 6 to 8

**Comment by kunokdev** [comment]
@TAQ2 just tried upgrading from 6 to 8 and memory leak is still present. Had to kill it before it fills my RAM completely and forces me to reboot by force. I tried few times to find issue but I couldn't because project is  too big, so I am trying to see what others have enabled to build reproductive example. **I also want to mention that leak is happening at the browser, not build process in my case**

![image](https://user-images.githubusercontent.com/13220754/29024590-0d8f10bc-7b73-11e7-859d-ae37f8463172.png)

**Comment by nmaro** [comment]
It happens in a number of projects, in my current one I'm not using .babelrc. No nodemon. Here's my package.json: https://github.com/nmaro/sorters/blob/master/package.json

**Comment by ebrearley** [comment]
This happened to me a few hours ago. I was utterly baffled cause I was only making superficial changes. Anyway, for me the problem was caused by accidentally thumbing the keyboard and creating a copy of `node_modules` in the `/pages` directory. No wonder the call stack overflowed.

I deleted the accidental rogue `node_modules` directory, back to normal.

**Comment by DaniellaGiovanna** [comment]
I just started trying out Next.js and the same thing is happening (Chrome as well as Firefox). I started in a clean directory, ran `npm install --save react react-dom next` and added a page `./pages/index.js` and a very basic component `./components/intro.js`. Both don't do anything special. The first includes the latter. 

It happened after a couple of hours _and_ several manual refreshes as well as restarts of the server as I was fiddling around with things, going through the docs and such. Not a single extra dependency was installed, no additional babel/webpack configs were made during the life of the project. 

See [this gist](https://gist.github.com/DaniellaGiovanna/57ac703f663c0f2bbb33e72e7fe9e26c) for the complete life of the project, from inception to errors.

**Comment by geryit** [comment]
Same problem here with chrome and firefox:

.babelrc:
```js
{
  "env": {
    "production": {
      "plugins": ["transform-remove-console"]
    }
  },
  "plugins": [
    "transform-decorators-legacy"
  ],
  "presets": [
    "next/babel",
    "stage-0"
  ],
  "ignore": []
}
```

package.json:
```js
"scripts": {
    "dev": "nodemon server.js --watch server.js --watch next.config.js  --watch package.json"
}
```

**Comment by nmaro** [comment]
Interestingly, this stopped happening with the newest firefox/next.

**Comment by flybayer** [comment]
Firefox 60 has become completely unusable for Next development on this project: https://github.com/beedesignllc/glutenproject.com, especially the `store` branch.

It's not long after loading the page and/or changes that Firefox gets super sluggish, requiring a Firefox restart.

But Chrome works great.

**Comment by kunokdev** [comment]
@nmaro Same here

**Comment by timneutkens** [comment]
I hope this is fixed by #4639, not entirely sure as I couldn't reproduce.

**Comment by devhyunjae** [comment]
I think this is the same issue
#5421
