### ISSUE TITLE
Why does this module build fail when using <style jsx>?

### ISSUE THREAD

**Issue by valnub** [zeit/next.js#2094]
The following code gives me this error:

> index.js?0c0f17f:97 Module build failed: SyntaxError: Expected a template literal or String literal as the child of the JSX Style tag (eg: <style jsx>{`some css`}</style>), but got Identifier

```jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import Colors from '../../Colors';

const containerStyle = `
  .containerStyle {
    position: fixed;
    width: 80%;
    right: 0;
    top: 0;
    bottom: 0;
    backgroundColor: ${Colors.NavigationBG};
  }
`;

class Navi extends Component {
  render() {
    const items = this.props.items;
    const itemsJsx = [];
    for (let i = 0; i < items.length; i += 1) {
      const itemJsx = (
        <div className="containerStyle">
          Navigation<br />
          {items[i].title}
          <style jsx>{containerStyle}</style>
        </div>
      );
      itemsJsx.push(itemJsx);
    }

    return (
      <div>
        {itemsJsx}
      </div>
    );
  }
}

Navi.propTypes = {
  items: PropTypes.array.isRequired,
};

export default Navi;
```

When I remove the `<style jsx>` part, then the error disappears. What's wrong?

I clearly assigned a string literal to the variable `containerStyle`, just as described in the docs. Why doesn't it work?

**Comment by albinekb** [comment]
If you replace `Colors.NavigationBG` with a variable local in the file

`const navBg = '#000' ` for example . Does it still not work?

**Comment by giuseppeg** [comment]
@valnub because that's not supported unfortunately. 
The CSS has to be inline:

```jsx
<div className="containerStyle">
  Navigation<br />
  {items[i].title}
  <style jsx>{`
    .containerStyle {
      position: fixed;
      width: 80%;
      right: 0;
      top: 0;
      bottom: 0;
      backgroundColor: ${Colors.NavigationBG};
    }
  `}</style>
</div>
```

This might change in the future since potentially it is possible to do what you tried here but it is not implemented in styled-jsx (mainly because we should think of edge cases and see if it'll work with the soon coming dynamic styles).

**Comment by valnub** [comment]
@giuseppeg Are you sure about that? There is an example in the docs which seems work without inline styles: https://github.com/zeit/styled-jsx#keeping-css-in-separate-files

![inline](https://cloud.githubusercontent.com/assets/3787662/26546973/fd43643e-446c-11e7-8e81-17e3ed40e7e9.jpg)

**Comment by valnub** [comment]
@albinekb I changed the code to this but had no effect:

```
const containerStyle = `
  .containerStyle {
    position: fixed;
    width: 80%;
    right: 0;
    top: 0;
    bottom: 0;
    backgroundColor: #000;
  }
`;
```

**Comment by valnub** [comment]
Here is a screenshot of the exact spot where the error occurs:

![err](https://cloud.githubusercontent.com/assets/3787662/26547038/513355ea-446d-11e7-9375-355c2246f165.jpg)

**Comment by giuseppeg** [comment]
> Are you sure about that

Yes

> There is an example in the docs which seems work without inline styles

That is styled-jsx v1.x which is still not used in Next.js (right now using 0.5.7). Even when Next.js will upgrade to 1.0.0 (very soon) you will be able to reference only external styles not files in the same file.

**Comment by valnub** [comment]
@giuseppeg Alright, thanks for pointing out. I think this should be fixed in the docs as it is a bit confusing right now.

**Comment by timneutkens** [comment]
@valnub we're working on it :)

**Comment by paulwehner** [comment]
So the docs are incorrect right now: https://github.com/zeit/styled-jsx#keeping-css-in-separate-files

The weird thing is that the docs above and having external styles with literal strings worked correctly with next 2.0.0, but doesn't work with 3.0.0-beta.

**Comment by kunokdev** [comment]
So if we use `<style jsx>{style}</style>` with external CSS or form other variable, it still doesn't work?
