### ISSUE TITLE
next/head unsetting _document <title>

### ISSUE THREAD

**Issue by IanMitchell** [zeit/next.js#3527]
I'm trying to add a custom Social component to my site that adds several relevant meta tags, but it's setting the `<title>` to an empty string. I have the title defined in `_document.js` and don't change it anywhere else in the codebase. I'm running the Canary version of Next.js

```javascript
import Document, { Head, Main, NextScript } from 'next/document'
export default class CustomDocument extends Document {
  static async getInitialProps (ctx) {
    return await Document.getInitialProps(ctx)
  }

  render () {
    return (
      <html lang="en">
        <Head>
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>Website Title</title>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

The custom component I call looks like this:

```javascript
import Head from 'next/head'

export default ({ title, image, description, url }) => (
  <Head>
    <meta key="twitter-card" name="twitter:card" content="summary" />
    <meta key="twitter-site" name="twitter:site" content="@ianmitchel1" />
    <meta key="twitter-title" name="twitter:title" content={title} />
    <meta key="twitter-description" name="twitter:description" content={description} />
    <meta key="twitter-image" name="twitter:image" content={image} />
    <meta key="twitter-url" name="twitter:url" content={url} />

    <meta key="facebook-type" property="og:type" content="article" />
    <meta key="facebook-title" property="og:title" content={title} />
    <meta key="facebook-description" property="og:description" content={description} />
    <meta key="facebook-image" property="og:image" content={image} />
    <meta key="facebook-url" property="og:url" content={url} />
  </Head>
)
```

It adds all the meta tags correctly (not sure if it's related, but I needed to add the `key` parameter - otherwise only the second set of meta tags was added) and the other meta tags from `_document.js` remain intact, but somehow the title tag just becomes `<title></title>`.

I've created a small example here - https://next-title-pnxpfydvvh.now.sh

**Comment by gsimone** [comment]
Same issue, running `4.2.1`

**Comment by gihrig** [comment]
I had this problem with 4.3.0-canary.1

It has been corrected as 4.4.0-canary.3

**Comment by timneutkens** [comment]
This is indeed a bug. This line show be wrapped in the if statement. I'll fix it once I'm done with universal webpack
https://github.com/zeit/next.js/blob/9320d9f006164f2e997982ce76e80122049ccb3c/client/head-manager.js#L33

**Comment by Sekhmet** [comment]
@timneutkens I can make PR for this if you don't mind.

**Comment by timneutkens** [comment]
@Sekhmet sure 👍

**Comment by remy** [comment]
I've just come across this and it's still present in next@5.0.1-canary.16. Example here: https://next-title-bug-kraxvxvjas.now.sh - [source](https://next-title-bug-kraxvxvjas.now.sh/_src)

**Comment by muzzofederico** [comment]
This is quite critical and still present. Any news?

**Comment by felipekm** [comment]
Same here, title and description appears in first glance but instantly goes away.

**Comment by JonathonJulian** [comment]
still an issue in 0.5.1, when will the fix be merged?

**Comment by ewagstaff** [comment]
Chiming in to say this appears to still be an issue. React is logging the correct value for <title> on render, but it appears blank after that.

**Comment by muzzofederico** [comment]
Help please. This is critical.

**Comment by JonathonJulian** [comment]
what seems to have worked for me was to add another <Head> </Head> with just the title in my component. weird seeing everything else from _document.js is there

**Comment by willcodes** [comment]
Having this issue in 5.01-canary.17. For now I will just duplicate the head on the pages that I need. Please fix one day :)

**Comment by ewagstaff** [comment]
JonathonJulian's solution seems pretty hacky. Is there a timetable on this being fixed for real?

**Comment by JonathonJulian** [comment]
Agreed, its not really a solution, a workaround at best, I ended up removing the title in _document as both tags were being picked up by google web crawlers

My site is pretty basic so not a big deal for me to to add to the pages and its better than no title, but still… pls fix,  surprised this was fixed in 6.0??

**Comment by timneutkens** [comment]
Closing this in favor of #4596 based on my comments in #3795
