### ISSUE TITLE
withStyles throws "React Hot Loader: this component is not accepted by Hot Loader."

### ISSUE THREAD

**Issue by sarkistlt** [zeit/next.js#3730]
works fine with next@4, having this issue after upgrading to next@5

https://github.com/mui-org/material-ui/issues/8821

**Comment by oliviertassinari** [comment]
I don't think it's a Material-UI only issue. This option can help: https://github.com/gaearon/react-hot-loader#disable-warnings.

**Comment by timneutkens** [comment]
Pretty interesting since we set `warnings={false}` on the AppContainer from react-hot-loader 😅

**Comment by timneutkens** [comment]
react-hot-loader is being released pretty often, so I've gave it a bump. Lets see if that fixes this 🙏

**Comment by timneutkens** [comment]
Either way @sarkistlt it's probably best to file an issue on react-hot-loader instead of on Next 👍

**Comment by sarkistlt** [comment]
yes it's not only Material-UI issue, and it has to do with react-hot-loader, sure can file an issue there as well but it also related to NextJS as react-hot-loader is a dependency and still requires patch from NextJS. upgrading to `react-hot-loader@4.0.0-beta.21` didn't help, actually opposite, have 2 more warnings:
  
<img width="1680" alt="screen shot 2018-02-08 at 9 52 20 am" src="https://user-images.githubusercontent.com/5773343/35989464-0de2c4b2-0cb6-11e8-9a8a-879ad7c1964f.png">

**Comment by theKashey** [comment]
These warnings are not a warning :(
React-hot-loaders replaces React.createElement method to do some magic inside. These errors means that there is some elements, which were created using "the real" React.createElement method. Or not from 'React' assessable by 'import from "React"'.
The simplest reason for this - you have 2 version of React underneath.
Try to find this second React, and, in case you cant just remove it,
```js
import reactHotLoader from 'react-hot-loader';
reactHotLoader.path(React)
```

**Comment by sarkistlt** [comment]
that's really odd, I don't have 2 version of React, and it works without any issue or warnings with next@4 which uses `react-hot-loader@3.1.1`, issue coming with next@5 and `react-hot-loader@4+`

**Comment by theKashey** [comment]
There is 141 common lines of code between react-hot-loader 3 and 4. So it's expected.
Just place a breakpoint in the problems component render, and step down into the React.createElement. Remember the location, and the do the same with component without errors. Now it first should dive into react-hot-loader, and then call the "real" React.createElement.

**Comment by sarkistlt** [comment]
I see what are you saying but it should be done in `NextJS` source code, not in the project, as `react-hot-loader` is `next` dependency and has nothing to do with my project. 
btw thanks for example above but again I think it should be placed in `NextJS`

**Comment by theKashey** [comment]
The simplest way, and sometimes the only usable way - use yarn `resolution` to force React stick to a single version.
Actually, it is legal to have 2 different Reacts, unless you have one react-dom, and maybe react-hot-loader should change its mind about this.

**Comment by timneutkens** [comment]
Actually @sarkistlt can you try `next@canary`. It might be a bundling issue that we fixed Wednesday.

@theKashey is there anything we should add to Next.js? It has the AppContainer + babel plugin at the moment, and it seemed to work fine for our app.

**Comment by theKashey** [comment]
@timneutkens so - react-hot-loader beta.21 is a bit "verbose" one, and you probably should upgrade to beta.22. But it does not exist yet :) (a day, or two)

**Comment by sarkistlt** [comment]
@timneutkens tried, same thing (one error about `WithStyles`)

**Comment by sarkistlt** [comment]
any update on this issue? still persist it in `5.0.1-canary.7`

**Comment by timneutkens** [comment]
React hot loader is no longer part of Next.js
