### ISSUE TITLE
'Symbol' is undefined in IE11 with Next v5.1.0

### ISSUE THREAD

**Issue by PrudviGali** [zeit/next.js#4187]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

App should work after upgrading to Next v5.1.0. in Next-js supported browsers.

## Current Behavior

Noticed ``` 'Symbol' is undefined``` issue in IE11 after upgrading to Next v5.1.0. We don't see this issue with Next v4.x.

## Steps to Reproduce (for bugs)

1. Upgrade app, which has for-of loop in its source code, to Nextv5.1.0.
2. Open the application in IE 11 after build process and check the dev console.

## Context

This is happening with Next v5.1.0.

Code generated for ```for-of``` loop with Next v5.1.0

```
for (var g = l[Symbol.iterator](), w; !(h = (w = g.next()).done); h = true) {                        
}
```

Next v4.x version with same source code.

```
for (var h, g = (0,r.default)(l); !(y = (h = g.next()).done); y = !0) {
}
```

We can fix the issue by adding ```babel-polyfill``` or ```babel runtime-transform``` to our code but it would be consistent if we have a solution as part of Next build.
 
## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    5.1.0     |
| node    |     8.11.1    |
| OS      |    windows     |
| browser |    IE 11     |
| etc     |         |

<img width="1075" alt="screen shot 2018-04-20 at 9 51 03 am" src="https://user-images.githubusercontent.com/10725504/39061558-49b228c8-448a-11e8-9fc9-6a79f3c90e22.png">

**Comment by quietshu** [comment]
Seems fixed in Next 6, cannot reproduce.

**Comment by matejkonrad** [comment]
This is an issue for me on Next 7.0.2 on IE11, Windows 10 (using browserstack)

**Comment by timneutkens** [comment]
@matejkonrad can you provide a full reproduction? I assume it's because you have a module in node_modules that uses `Symbol`

**Comment by timneutkens** [comment]
I'm going to close this.

**Comment by itsfadnis** [comment]
@timneutkens I'm facing the same issue as well. I have a couple node_modules that use `Symbol`. I've polyfilled `Symbol` from `core-js`. I still get this error:

![screen shot 2019-01-16 at 12 24 15 pm](https://user-images.githubusercontent.com/5605495/51231500-b2a6ca80-1989-11e9-8073-f7c0d91a828c.png)

I'm facing this issue on IE 11. Any pointers? I'm not sure what I'm missing.

**Comment by nishtacular** [comment]
@itsfadnis were you able to resolve this?

**Comment by itsfadnis** [comment]
> @itsfadnis were you able to resolve this?

Yes, using the symbol polyfill got the job done.
