### ISSUE TITLE
Next.js 9.1.7 Impossible to test next/link with enzyme mount.

### ISSUE THREAD

**Issue by gudvinga** [zeit/next.js#9951]
# Bug report
Impossible to test next/link with enzyme mount.

## Describe the bug
When trying to test a component with next/link using an enzyme mount, an error occurs 

`Error: Uncaught [TypeError: Cannot read property 'pageLoader' of null]. `

The error is only in version 9.1.7, in previous versions everything was fine.

## To Reproduce
repository to reproduce
[https://github.com/gudvinga/next-9.1.7-link-jest-enzyme](https://github.com/gudvinga/next-9.1.7-link-jest-enzyme)

1. yarn install
2. yarn test
3. See error

## Expected behavior
Should work without error.

## System information
- Version of Next.js: 9.1.7

**Comment by Erazihel** [comment]
Got the same error using React Testing Library:
```
  ● Component › should render correctly

    TypeError: Cannot read property 'pageLoader' of null

       6 | describe("Component", () => {
       7 |   it("should render correctly", () => {
    >  8 |     const { getByText } = render(<Component />);
         |                           ^
       9 |
      10 |     expect(getByText("Hello World")).toBeDefined();
      11 |   });

      at Link.handleRef (packages/header/node_modules/next/dist/client/link.js:8:710)
```
Using Next@9.1.6 does not throw that error.

**Comment by remisture** [comment]
Happens to me as well. Any fix available other than using 9.1.6?

**Comment by AlexanderEerenberg** [comment]
For me this also happened in Next 9.1.6. It appeared my **@types/node** was updated to _13.0.0_ which yielded the exact same error in my tests (react testing library). After reverting back **@types/node** to _12.12.22_ all was fine.

I tested Next 9.1.7 afterwards but the error remains the same so I'm sticking to Next 9.1.6 with @types/node 12.12.22 for now.

**Comment by gudvinga** [comment]
This error occurs because the next/router is not initialized, perhaps this has something to do with prefetch in the next/link

**Comment by lednhatkhanh** [comment]
Facing exact same problem with `@testing-library/react`

**Comment by ajcrews** [comment]
Here is the line causing the issue: https://github.com/zeit/next.js/pull/9644/files#diff-9d07cd98332d8743307195c93020bb17R139

This could simply be made more defensive instead of assuming there is a router reference.

**Comment by pjaws** [comment]
Also seeing this with React Testing Library. This is a complete blocker for me and anyone else doing automated testing (which should be everyone). Hope you guys release 9.1.8 soon.

**Comment by aviaryan** [comment]
Can anyone confirm if [9.1.8-canary](https://www.npmjs.com/package/next/v/9.1.8-canary.5) fixed this issue for them? I still see the same error but I am new to Next.js so it can be because of some other reason.

**Comment by Timer** [comment]
This should be fixed in `v9.1.8-canary.6` — please check!

**Comment by aviaryan** [comment]
Works for me.

**Comment by janhoogeveen** [comment]
Our tests pass on v9.1.8-canary.6 👍

**Comment by amclin** [comment]
Works for me with `react-test-renderer`

**Comment by JoaoFGuiomar** [comment]
It seems all my components that were using useContext are failing now.

Example:

```jsx
const APP_PROVIDER_DATA = {
    data: {
        currency: '€',
    },
};

describe('<InformationBoard />', () => {
    it('should render properly', () => {
        const { container } = render(
            <AppProvider data={APP_PROVIDER_DATA }>
                <SomeComponent />
            </AppProvider>
        );
}

```

<SomeComponent /> uses "useContext" to get the currency symbol but all it gets is an empty object.

Currently testing with v9.1.8-canary.7

**Comment by Timer** [comment]
@JoaoFGuiomar that sounds unrelated to this issue. If you believe you've encountered a bug, please open a new issue with a full reproduction.

**Comment by Timer** [comment]
Locking this to prevent notification spam as multiple users have confirmed it as resolved! Thank you everyone. 😄
